### ISSUE TITLE
Store validator preferences and resend them at a regular interval

### ISSUE THREAD

**Issue by 0xpanoramix** [flashbots/mev-boost#141]
## Description

One of the features mentioned in #95 is to store the validator preferences (preferred fee recipient and gas limit for a given validator) and then send them at a regular interval to the relays.

As there are many ways to implement this feature, I think it could be interesting to have a discussion about which one is the best.

## 1 : Use a separate goroutine

We can have a goroutine which reads the registered preferences in a safe map and sends those values to the relays at a regular interval, something like :

```golang

// BoostService TODO
type BoostService struct {
	// Backend stuff...

	// The validators preferred fee recipient and gas limit
	mu          sync.RWMutex
	preferences map[string]types.SignedValidatorRegistration
}

// sendValidatorPreferencesAtInterval is launched as a goroutine
func (m *BoostService) sendValidatorPreferencesAtInterval(done chan bool) {
	ticker := time.NewTicker(time.Minute)
	defer ticker.Stop()

	for {
		select {
		case <-done:
			return

		case <-ticker.C:
			// Loads preferences from map after declaration
			payload := []types.SignedValidatorRegistration{}
			
			// Send to each relay
			for _, relay := range m.relays {
				err := SendHTTPRequest(context.Background(), m.httpClient, http.MethodPost, url, payload, nil)
			}
		}
	}
}

func (m *BoostService) handleRegisterValidator(w http.ResponseWriter, req *http.Request) {
	// ...
	for _, registration := range payload {
		// Sanity checks...
		
		// Stores the SignedValidatorRegistration and maps it to the validator's public key
		m.mu.Lock()
		m.preferences[registration.Message.Pubkey.String()] = registration
		m.mu.Unlock()
	}
	// ...
}
```

I'd like to have your opinion about this, or if you have a better solution !

**Comment by metachris** [comment]
That sounds like a good approach! Happy to go that direction 👍

**Comment by 0xpanoramix** [comment]
I have implemented this in #149, but I'm still wondering where to start the goroutine.

I was thinking about [here](https://github.com/0xpanoramix/mev-boost/blob/fa367969d833ce57c63c5c94e3b3abc7992d25a9/server/service.go#L112), what's your opinion on this ?

And what should be the name of a new CLI flag used to provide this interval, if we need one at all (as it could be a hardcoded value).

cc @metachris

**Comment by metachris** [comment]
That place to start the goroutine looks good 👍 Maybe rename the function to `startServer`.

Cli flag or only env var for now... Not having a strong opinion. Maybe something like `validatorregistrations-resend-interval-sec` but that's soo long. maybe start with only an env var override like `VALIDATOR_REGISTRATIONS_SEND_INTERVAL_SEC` 🤔

**Comment by 0xpanoramix** [comment]
Thanks @metachris ! I've used `register-validator-interval`, I think it's short and explains well what the flag actually does.
The PR is marked as ready for review, feel free to take a look at it !

**Comment by metachris** [comment]
Thanks Luca! As discussed, closing this for now in favour of having the validators do the resending, and keeping this complexity out of mev-boost. One question was at which point to remove old registrations, to not keep them around forever.
