### ISSUE TITLE
File support for relay urls

### ISSUE THREAD

**Issue by jmcruz1983** [flashbots/mev-boost#155]
Could relays urls specification be stored in a file 
and mev-boost would read from there?

That would add better support for multiple relay sources,

And could that file be reloaded on a given period? 
could that period be configured?

**Comment by metachris** [comment]
Yes, that sounds like a good idea.

**Comment by ricardolyn** [comment]
if [this](https://github.com/flashbots/mev-boost/issues/154) setup is done, might not be necessary to do file support if the service is able to pull from a remote URL.

**Comment by metachris** [comment]
Closing this in favor of tracking all in issue #154
