### ISSUE TITLE
Support mev-boost in teku

### ISSUE THREAD

**Issue by come-maiz** [flashbots/mev-boost#156]
Here we track the support of mev-boost in [teku](https://github.com/ConsenSys/teku). 

:heavy_check_mark: Builder API
:heavy_check_mark: [local fallback when builder not available](https://github.com/ConsenSys/teku/pull/6015) 
:question: local profit comparison
:heavy_check_mark: [circuit breaker](https://github.com/ConsenSys/teku/pull/6083)

https://docs.teku.consensys.net/en/latest/HowTo/Builder-Network/

**Comment by elopio** [comment]
[tbenr](https://github.com/tbenr) and [StefanBratanov](https://github.com/StefanBratanov) are the humans writing the code for  mev-boost in teku.

# Merged work

- https://github.com/ConsenSys/teku/pull/5110
- https://github.com/ConsenSys/teku/pull/5111
- https://github.com/ConsenSys/teku/pull/5112
- https://github.com/ConsenSys/teku/pull/5132
- https://github.com/ConsenSys/teku/pull/5175
- https://github.com/ConsenSys/teku/pull/5249
- https://github.com/ConsenSys/teku/pull/5273
- https://github.com/ConsenSys/teku/pull/5298
- https://github.com/ConsenSys/teku/pull/5341
- https://github.com/ConsenSys/teku/pull/5351
- https://github.com/ConsenSys/teku/pull/5406
- https://github.com/ConsenSys/teku/pull/5417
- https://github.com/ConsenSys/teku/pull/5428
- https://github.com/ConsenSys/teku/pull/5429
- https://github.com/ConsenSys/teku/pull/5458
- https://github.com/ConsenSys/teku/pull/5489
- https://github.com/ConsenSys/teku/pull/5499
- https://github.com/ConsenSys/teku/pull/5521
- https://github.com/ConsenSys/teku/pull/5528
- https://github.com/ConsenSys/teku/pull/5535
- https://github.com/ConsenSys/teku/pull/5537
- https://github.com/ConsenSys/teku/pull/5545
- https://github.com/ConsenSys/teku/pull/5573
- https://github.com/ConsenSys/teku/pull/5584
- https://github.com/ConsenSys/teku/pull/5585
- https://github.com/ConsenSys/teku/pull/5597
- https://github.com/ConsenSys/teku/pull/5598
- https://github.com/ConsenSys/teku/pull/5612
- https://github.com/ConsenSys/teku/pull/5624
- https://github.com/ConsenSys/teku/pull/5641
- https://github.com/ConsenSys/teku/pull/5642
- https://github.com/ConsenSys/teku/pull/5643
- https://github.com/ConsenSys/teku/pull/5649
- https://github.com/ConsenSys/teku/pull/5664
- https://github.com/ConsenSys/teku/pull/5679
- https://github.com/ConsenSys/teku/pull/5692
- https://github.com/ConsenSys/teku/pull/5693
- https://github.com/ConsenSys/teku/pull/5695
- https://github.com/ConsenSys/teku/pull/5714
- https://github.com/ConsenSys/teku/pull/5715
- https://github.com/ConsenSys/teku/pull/5721
- https://github.com/ConsenSys/teku/pull/5722
- https://github.com/ConsenSys/teku/pull/5732
- https://github.com/ConsenSys/teku/pull/5758
- https://github.com/ConsenSys/teku/pull/5777
- https://github.com/ConsenSys/teku/pull/5788

**Comment by elopio** [comment]
@StefanBratanov prepared this guide for testing: 

https://hackmd.io/@StefanBratanov/BkMlo1RO9

Teku is ready for testing in Kiln.

**Comment by elopio** [comment]
Issues found during testing:
- https://github.com/ConsenSys/teku/issues/5884
- https://github.com/ConsenSys/teku/issues/5885
