### ISSUE TITLE
Support mev-boost in lodestar

### ISSUE THREAD

**Issue by come-maiz** [flashbots/mev-boost#157]
Here we track the support of mev-boost in [lodestar](https://github.com/ChainSafe/lodestar).

**Comment by elopio** [comment]
@g11tech, @dapplion, and @tuyennhv are the humans writing the code for mev-boost in lodestar.

# Work in progress

https://github.com/ChainSafe/lodestar/pull/3969

**Comment by come-maiz** [comment]
Issues found during testing:

- https://github.com/ChainSafe/lodestar/issues/4394

**Comment by g11tech** [comment]
> Issues found during testing:
> 
>     * [MaxListenersExceededWarning: Possible EventTarget memory leak detected. ChainSafe/lodestar#4394](https://github.com/ChainSafe/lodestar/issues/4394)
> 
>     * [error: Error updating eth1 chain cache  Timeout request ChainSafe/lodestar#4395](https://github.com/ChainSafe/lodestar/issues/4395)
> 
>     * [Chain logs "expected" errors ChainSafe/lodestar#3062 (comment)](https://github.com/ChainSafe/lodestar/issues/3062#issuecomment-1211457758)

thanks @come-maiz for reporting issues, most of these are harmless/self recoverable issues not liked with mev-boost, we have plans to improve our error UX and will keep you updated as we improve the experience. Do update any other issues you are facing. :pray:

**Comment by come-maiz** [comment]
Thank you @g11tech. My beacon node has 3 more days left for syncing. I'll share anything weird that happens.

**Comment by g11tech** [comment]
> Thank you @g11tech. My beacon node has 3 more days left for syncing. I'll share anything weird that happens.

which networ are you syncing? may be I can provide you with a weak subjectivity sync encpoint to start off easily with

**Comment by come-maiz** [comment]
I'm in kiln. Now I should actually stop and restart with goerli. And yes please, how do I make this faster? :)

**Comment by g11tech** [comment]
> I'm in kiln. Now I should actually stop and restart with goerli. And yes please, how do I make this faster? :)

DM me on discord pls (11crygpt)
