### ISSUE TITLE
Support mev-boost in prysm

### ISSUE THREAD

**Issue by come-maiz** [flashbots/mev-boost#158]
Here we track the support of mev-boost in [Prysm](https://github.com/prysmaticlabs/prysm/).

:heavy_check_mark: Builder API
:question: local fallback when builder not available 
:question: local profit comparison
:heavy_check_mark: [circuit breaker](https://github.com/prysmaticlabs/prysm/pull/11215)

@terencechain prepared this guide: https://hackmd.io/@prysmaticlabs/BJeinxFsq

**Comment by elopio** [comment]
@terencechain, @james-prysm, and @kasey are the humans writing the code for mev-boost in prysm.

# Issues in the prysm repository

- https://github.com/prysmaticlabs/prysm/issues/10593

# Merged work

- https://github.com/prysmaticlabs/prysm/pull/10703
- https://github.com/prysmaticlabs/prysm/pull/10749
- https://github.com/prysmaticlabs/prysm/pull/10883

**Comment by metachris** [comment]
Implementation of the builder-specs is now complete in Prysm, and merged in the develop branch.

**Comment by elopio** [comment]
Issues found during testing:
- https://github.com/prysmaticlabs/prysm/issues/8072#issuecomment-1176974147
- https://github.com/prysmaticlabs/prysm/issues/10999
- https://github.com/prysmaticlabs/prysm/issues/11000

**Comment by james-prysm** [comment]
@elopio responded to the kiln question, wondering if that answered you.

**Comment by elopio** [comment]
Yes! Thanks @james-prysm. I'm getting a new testing machine and then I will give a try to everything and update the testing guide. I'll report on your repo any findinds.
