### ISSUE TITLE
Support mev-boost in nimbus

### ISSUE THREAD

**Issue by come-maiz** [flashbots/mev-boost#159]
Here we track the support of mev-boost in [nimbus](https://github.com/status-im/nimbus-eth2).

**Comment by elopio** [comment]
@tersec, @arnetheduck, and @zah are the humans writing the code for mev-boost in nimbus.

# Issues in the nimbus repository

- https://github.com/status-im/nimbus-eth2/issues/3200

# Merged work

- https://github.com/status-im/nimbus-eth2/pull/3620
- https://github.com/status-im/nimbus-eth2/pull/3621
- https://github.com/status-im/nimbus-eth2/pull/3622
- https://github.com/status-im/nimbus-eth2/pull/3625

# Work in progress

- https://github.com/status-im/nimbus-eth2/pull/3694
-
