### ISSUE TITLE
Support mev-boost in lighthouse

### ISSUE THREAD

**Issue by come-maiz** [flashbots/mev-boost#160]
Here we track the support of mev-boost in [lighthouse](https://github.com/sigp/lighthouse).

:heavy_check_mark: Builder API
:question: local fallback when builder not available 
:heavy_check_mark: [local profit comparison](https://github.com/sigp/lighthouse/pull/3534)
:heavy_check_mark: [circuit breaker](https://github.com/sigp/lighthouse/pull/3134/files#diff-c15ca8b30f33ec7edc5fb1d021f71ad868db71da74ec3e8e1ab81186a3bafe72R4560)

https://lighthouse-book.sigmaprime.io/builders.html
Guide to testing the unstable integration: https://mirror.xyz/ladislaus.eth/ah5UOhcstfmnk5rzTBQ-e26XudUqmxr3flnkLqlEDYE

**Comment by elopio** [comment]
@realbigsean is the human writing the code for mev-boost in lighthouse.

# Issues in the lightclient repository

- https://github.com/sigp/lighthouse/pull/2987
- https://github.com/sigp/lighthouse/issues/3091

 # Merged work

- https://github.com/sigp/lighthouse/pull/3062

# Work in progress

- https://github.com/sigp/lighthouse/pull/3134

**Comment by paulhauner** [comment]
The latest Lighthouse release contains v0.2.0 builder API support :tada: 

https://github.com/sigp/lighthouse/releases/tag/v2.5.0
