### ISSUE TITLE
Publish the mev-boost call for testing

### ISSUE THREAD

**Issue by elopio** [flashbots/mev-boost#163]
Once mev-boost is ready for testing in kiln we will publish an announcement to get more validators to try it and provide feedback.

**Comment by elopio** [comment]
mev-boost is now ready, implementing the builder api v0.1.0.
We have a relay and a builder already setup in kiln and ropsten.
Teku is now ready for testing. #156.

**Comment by elopio** [comment]
Should we wait for more validators before the call for testing? 
I think we shouldn't. We don't have a lot of time for testing, and the earlier we start the better. I think we should publish this on tuesday or wednesday, the latest. We can provide a link to generic test steps and a link to the [consensus client implementation status](https://github.com/flashbots/mev-boost/blob/3b84e3b84ec586129a1d7dadd9f8db674f196d36/README.md#consensus-clients-implementation-status). Then, as new clients are ready, we make more noise to celebrate and give more force to the testing call.

**Comment by elopio** [comment]
Should we make a call for testing only in kiln?
I think so. If we announce this for all networks then it will be hard to focus the energy. Not all of the test networks will have mev opportunities or searchers sending transactions. If we focus on kiln, we can get realistic end-to-end scenarios.

**Comment by elopio** [comment]
Call for testing ready for review:
https://github.com/flashbots/flashbots-writings-website/pull/22

**Comment by elopio** [comment]
The testing guide is in progress:
https://github.com/flashbots/mev-boost/wiki/Testing#tekunethermindmev-boost

**Comment by ladidan** [comment]
I've summarised my findings testing mev-boost in conjunction with Lighthouse+Besu and docker-compose on Ropsten here:
https://mirror.xyz/ladislaus.eth/ah5UOhcstfmnk5rzTBQ-e26XudUqmxr3flnkLqlEDYE

**Comment by elopio** [comment]
Published :)

https://writings.flashbots.net/writings/mev-boost-call-for-testing
