### ISSUE TITLE
Should mev-boost disable validator registration signature verification and leave that to the relay?

### ISSUE THREAD

**Issue by metachris** [flashbots/mev-boost#170]
Currently mev-boost verifies the signatures on each registerValidator entry, and errors if any one is incorrect. This costs resources and perhaps this task should be left to the relay after all? I'm slightly leaning towards disabling the verification in mev-boost. Any thoughts?

**Comment by tbenr** [comment]
I'm for it. I don't see any particular benefit by verifying the signature in mev-boost.

**Comment by metachris** [comment]
implemented in #176
