### ISSUE TITLE
Faucet doesn't seem to be working even with my ENS name

### ISSUE THREAD

**Issue by klovertexarkana** [flashbots/mev-boost#196]
Here is my address: 0x320D24BEA15B5A72839d608Dfc95ed85c9d8afc0

I have two ENS domains and neither seemed to work. I do have Kiln set up for metamask. Thanks for any help you can provide.

**Comment by metachris** [comment]
This is the wrong repository for that kind of issue.

**Comment by klovertexarkana** [comment]
The link on this guide: https://github.com/flashbots/mev-boost/wiki/Testing
directs me here to ask for testnet ETH. If you look at the guide under "Register as a vaalidator" there is a link within the statement:

Get kiln ether from the [faucet](https://faucet.kiln.themerge.dev/). When the funds are low, this requires an ENS domain. If you don't have one, [ask us for some test ether opening an issue](https://github.com/flashbots/mev-boost/issues/new).

**Comment by elopio** [comment]
Hello @klovertexarkana.

I've sent you 32 kiln test ether. Please let us know how your testing goes :)

**Comment by klovertexarkana** [comment]
Thank you so much!!

Would you mind sending me the transaction hash? I’m so confused bc there isn’t showing any in my metamask account at this time.

Perhaps the faucet is working. I’m on the Kiln network and I copy-pasted my address. I’m not sure why it hasn’t arrived. I hold other assets in mainnet, polygon, goerli, and rinkeby.
