### ISSUE TITLE
Link on mev-boost testing guide which was edited 4 hours ago directs me here to ask for kiln testnet ETH

### ISSUE THREAD

**Issue by klovertexarkana** [flashbots/mev-boost#197]
Here is the link: https://github.com/flashbots/mev-boost/wiki/Testing

Scroll down to "Register as a validator". Under "Kiln":

1. Get kiln ether from the [faucet](https://faucet.kiln.themerge.dev/). When the funds are low, this requires an ENS domain. If you don't have one, [ask us for some test ether opening an issue](https://github.com/flashbots/mev-boost/issues/new).

Please advise or update guide to the correct place to "ask us for somee test ether..."

**Comment by elopio** [comment]
I've updated the guide to link to this: https://github.com/flashbots/mev-boost/issues/199
