### ISSUE TITLE
Improve tutorial for testing

### ISSUE THREAD

**Issue by adv0r** [flashbots/mev-boost#198]
Some things that come to mind might be evident for most of you, but not for 100% of validators:

 * specify if there are any hardware requirements. 
 * specify if mev-boost must be installed on the consensus machine or the execution machine, both, or maybe whether geth+lighthouse must be on the same machine 
 * specify for which consensus client it works at the beginning of the tutorial... I spent considerate amount of time to find in the end it doesn't currently support lighthouse ;) 
 * specify that you'd need 32 test ETH, meaning that on the faucet links you provide it will take 24 days to gather them for users starting from zero...  (hopefully the merge already happened by then)

**Comment by elopio** [comment]
Hello @adv0r. Thanks for reporting this.

- specify if there are any hardware requirements.

They are in the [validator checklist](https://launchpad.ethereum.org/en/checklist). And then every development team should have the requirements on their docs. We can start measuring the specifics of mev-boost to also document the requirements. #201

- specify if mev-boost must be installed on the consensus machine or the execution machine, both, or maybe whether geth+lighthouse must be on the same machine

It can be installed anywhere, as long as is reachable by the consensus client. We can mention this in our docs, somewhere :thinking: #202

- specify for which consensus client it works at the beginning of the tutorial... I spent considerate amount of time to find in the end it doesn't currently support lighthouse ;)

done

- specify that you'd need 32 test ETH, meaning that on the faucet links you provide it will take 24 days to gather them for users starting from zero... (hopefully the merge already happened by then)

I've linked the guide to #199.
