### ISSUE TITLE
Where to get test ether?

### ISSUE THREAD

**Issue by elopio** [flashbots/mev-boost#199]
In order to test a validator you will need 32 test ether from the network you want to test.

Here is the kiln faucet: https://faucet.kiln.themerge.dev/

Here are some ropsten faucets:
- https://faucet.metamask.io/
- https://faucet.egorfine.com/
- https://faucet.dimensions.network/
- https://ropsten.chain.link/
- https://faucet.paradigm.xyz/

When the funds are low, it might be harder to get test ether. If you have problems with one of the faucets let us know so other testers are aware. If you can't get to 32 ether let us know and we'll try to help you if we have surplus. If you have plenty of test ether, please let us know and share it with the others :)

**Comment by adv0r** [comment]
i'd like to get some klin eth @ noster.eth if possible. thanks

for ropsten this was fast -> https://ropsten-faucet.pk910.de/

**Comment by klovertexarkana** [comment]
Nevermind!! It just showed up!! 

I hope 32 is enough though. Won’t I need to cover gas for the deposit?

**Comment by pk910** [comment]
PoW Faucet is available for Kiln too:  https://kiln-faucet.pk910.de/

Same difficulty as for the Ropsten one. So it's not very hard to get 35 ETH for a validator.
The official faucets were drained by bots 🙄

**Comment by klovertexarkana** [comment]
Hope I’m not being a bother, but how did you send test ether to my GitHub account? Do you know what address it was sent to?
