### ISSUE TITLE
getHeader and submitBlindBlock latencies

### ISSUE THREAD

**Issue by terencechain** [flashbots/mev-boost#203]
Not sure if this is the best place to track this. Feel free to close this and let me know a more appropriate place, we can move the issue somewhere else. 

I've been observing high latencies with both getStatus, getHeader and submitBlindBlock calls using the Kiln relay.

getStatus, between 100-500ms
<img width="1345" alt="Screen Shot 2022-07-11 at 2 34 00 PM" src="https://user-images.githubusercontent.com/21316537/178362622-48269eed-47c2-4821-8307-6acccb7c0f6c.png">

getHeader, this gotten worse in the last 24 hours, many calls exceeded 1-2s
<img width="1350" alt="Screen Shot 2022-07-11 at 2 33 26 PM" src="https://user-images.githubusercontent.com/21316537/178362784-72cbabd3-2b97-4291-9d7d-cbcd5ded0814.png">

submitBlindBlock, mostly around 200ms
<img width="1356" alt="Screen Shot 2022-07-11 at 2 32 49 PM" src="https://user-images.githubusercontent.com/21316537/178362846-f35e8f09-7805-4281-a805-db23e6904511.png">

This is a prysm beacon node getting a beacon block for validator to sign. We are seeing 10-25x latency increases
<img width="1700" alt="Screen Shot 2022-07-11 at 2 37 25 PM" src="https://user-images.githubusercontent.com/21316537/178362942-b90e7831-ec6a-4639-a5fa-2b0d24377d12.png">
 
I understand that many moving parts are currently under optimized, but I still want to open an issue for tracking

**Comment by metachris** [comment]
That's great, thank you for reporting. Well investigate today and update here.

**Comment by terencechain** [comment]
`getHeader` has gotten much better 🎉 
![Screen Shot 2022-07-13 at 8 09 37 AM](https://user-images.githubusercontent.com/21316537/178768900-7a8c3eb8-fba8-48ed-a7b4-90c262807f17.png)

`submitBlindBlock` and `getStatus` are pretty much the same as before. 95% percentile still around ~200-500ms.
We won't be calling `getStatus` anymore. Only once during startup so that's not going to be an issue for us. Let me know if you want me to close this and just track `submitBlindBlock` separately

**Comment by tbenr** [comment]
Last 24h for us on Ropsten.
Focus on the pies, we had 6 slow responses (between 1s and 2s) for `GetHeader` and 3 slow (between 300 and 500 ms) for `GetPayload`

<img width="1836" alt="image" src="https://user-images.githubusercontent.com/15999009/178803616-f3082277-4033-46dc-9544-54b082e3ed58.png">

**Comment by tbenr** [comment]
registration response time improved significantly

![image](https://user-images.githubusercontent.com/15999009/178806375-f32c6b92-8d38-4e01-8146-679bedf281a4.png)

**Comment by metachris** [comment]
@tbenr @terencechain do you have any current charts for the last days/week?

**Comment by tbenr** [comment]
Last 2 days in sepolia:
<img width="867" alt="image" src="https://user-images.githubusercontent.com/15999009/180441264-28186bf9-2159-4f8a-9042-e214027506bc.png">
<img width="870" alt="image" src="https://user-images.githubusercontent.com/15999009/180441340-862a5f4f-1641-41d9-b786-27e62e33325b.png">
