### ISSUE TITLE
Allow nonexistent validators use the testnet relays

### ISSUE THREAD

**Issue by tersec** [flashbots/mev-boost#207]
It remains useful to have at least one of https://builder-relay-sepolia.flashbots.net/ and https://builder-relay-ropsten.flashbots.net/ to allow nonexistent validators and proposals on slots they're not allowed to propose for testing flows. This now returns, e.g.,
> {"code":400,"message":"not a known validator: 0xa6d310dbbfab9a22450f59993f87a4ce5db6223f3b5f1f30d2c4ec718922d400e0b3c7741de8e59960f72411a0ee10a7"}

from `registerValidator`. This is not false, but hinders testing.

For example, both `mergemock` and https://github.com/flashbots/boost-geth-builder require `forkchoiceUpdated` in a way the flashbots.net-deployed analogs don't:
> Requires forkchoice update to be sent for block building, on public testnets run beacon node modified to send forkchoice update on every slot example modified beacon client (lighthouse)

A modified client isn't the ideal thing to test in this context, so these local devnet alternatives are less than ideal.

This wouldn't necessarily have to be on the same endpoints, or could be distinguished in some way.

**Comment by metachris** [comment]
We can probably enable this functionality in sepolia. Will discuss internally and give an update tomorrow.

**Comment by metachris** [comment]
@tersec has already completed integration, closing this now.
