### ISSUE TITLE
gcc compiler

### ISSUE THREAD

**Issue by MareG76** [flashbots/mev-boost#227]
Please add in installation section that gcc compiler need to be installed on Windows so GO can install it successfully

**Comment by metachris** [comment]
could you post full windows instructions here?

**Comment by MareG76** [comment]
Hello, I can tell you how I did it but my English is little rusty.
I installed GO from https://go.dev/doc/install 
after that for some reason I couldn't install MinGW-W64 via online installer so i downloaded the x86_64-posix-seh file from this page: https://sourceforge.net/projects/mingw-w64/files/mingw-w64/
and use 7zip to unzip it directly to C folder then i copied the path to bin folder in it which is c:\mingw64\bin. Now in windows search bar type "Edit the system environment variables" and click on it, select "Environment Variables" on bottom right corner , in user varibles section select "Path" and click "Edit", now click "New" and paste here the path to bin folder( in my case c:\mingw64\bin, depend where it is extracted) click "Ok" three times and after that you are redy to install mev-boost with "go install github.com/flashbots/mev-boost@latest" via command prompt

**Comment by metachris** [comment]
thanks! these should be documented in the Go installation instructions themselves, we don't currently have the bandwidth to maintain windows instructions.
