### ISSUE TITLE
RPC error logging

### ISSUE THREAD

**Issue by terencechain** [flashbots/mev-boost#23]
We use the standard library `log.Println` to log RPC server errors. I'd consider something more exotic like `go-ethereum/log` or `sirupsen/logrus` so we can do something like `log.Warn...`

**Comment by jparyani** [comment]
Ya, I agree moving to a better logging library would help. I've used logrus and zap in the past, and both were great. I wouldn't be opposed to go-ethereum/log either

**Comment by terencechain** [comment]
I can take a stab at it if no one else is working on it

**Comment by jparyani** [comment]
Yep go for it, and feel to pick any of the above logging libraries
