### ISSUE TITLE
Should mev-boost have a default mainnet relay?

### ISSUE THREAD

**Issue by come-maiz** [flashbots/mev-boost#246]
When we just run `mev-boost`, should it connect to a default trusted relay?

Or should the validators always pass in an argument the URL and public key of the relay they want to connect to?

**Comment by come-maiz** [comment]
For a discussion on configuration relay options, see #186.

**Comment by allboxes** [comment]
If the only candidate default relays are required to blacklist/censor (https://github.com/flashbots/rpc-endpoint/issues/98), then I think a small UX hundle is feature here.  

Flashbots' stated goal is to reduce erosion of "neutrality, transparency, decentralization, and permissionlessness."
 
A default relay with permissioned transactions works directly again 3 of those goals.

MEV-Boost, by itself, creates a alternative pathway for validators to extract MEV if they so desire, in theory guiding them away from large pools.  Without a default relay, validators motivated to extract MEV are forced to actively choose a relay and can evaluate it's merits in a decentralized way.

MEV-Boost must either not have a default relay, or the default must be neutral and permissionless towards transactions.

If Flashbots is unable to run a relay that meets these requirements, I hope they will stand by their stated goals and not force their relay on MEV-Boost users and on the Ethereum ecosystem.

**Comment by pappas999** [comment]
> MEV-Boost must either not have a default relay, or the default must be neutral and permissionless towards transactions.
> 
> If Flashbots is unable to run a relay that meets these requirements, I hope they will stand by their stated goals and not force their relay on MEV-Boost users and on the Ethereum ecosystem.

this 100%!

**Comment by metachris** [comment]
We've decided against having a default relay. Closing now.
