### ISSUE TITLE
Incorrect parsing of attester slashing indices in relay

### ISSUE THREAD

**Issue by michaelsproul** [flashbots/mev-boost#247]
This is more of an issue with the flashbots relay than `mev-boost` itself, but in lieu of another repo to open an issue on I'm opening it here.

On the Lighthouse Discord we had a user report a block proposal failure using `mev-boost`:

> Aug 11 22:54:36.902 ERRO Error whilst producing a blinded block, cannot fallback because the block was signed, error: "All endpoints failed http://localhost:5952/ => RequestFailed(Irrecoverable(\"Error from beacon node when publishing block: ServerMessage(ErrorMessage { code: 500, message: \\\"INTERNAL_SERVER_ERROR: Blind block proposal failed: Builder(ServerMessage(ErrorMessage { code: 400, message: \\\\\\\"json: cannot unmarshal string into Go struct field IndexedAttestation.message.body.attester_slashings.attestation_1.attesting_indices of type uint64\\\\\\\", stacktraces: [] }))\\\", stacktraces: [] })\"))", service: block

Source: https://discord.com/channels/605577013327167508/605577013331361793/1007508047586926682.

I believe this indicates that the relay is trying to deserialize the `attesting_indices` of the attester slashing as a JSON `number` rather than a bignum `string` (the canonical representation that Lighthouse uses). Beacon nodes will always encode validator indices as quoted bignums, see e.g. https://ethereum.github.io/beacon-APIs/#/Beacon/getPoolAttesterSlashings.

This means that all blocks containing attester slashings will fail when the beacon node attempts to publish them, a rather significant liveness failure. Thankfully I think it should be easy to fix, the relay should fix its parsing of `attesting_indices` for the [`POST /eth/v1/builder/blinded_blocks` endpoint](https://ethereum.github.io/builder-specs/#/Builder/submitBlindedBlock).

**Comment by michaelsproul** [comment]
Apologies, this is a duplicate of https://github.com/flashbots/go-boost-utils/issues/18 and seems to be fixed in the most recent versions of `mev-boost` and the relay.

**Comment by michaelsproul** [comment]
The user claimed to be running https://github.com/flashbots/mev-boost/commit/e83a51b0970461c48b348d5dab3334115db044b0, which would seem to include the fix? My Go-fu isn't strong enough to determine whether we should expect the fix to already be included in that commit. Or maybe it is the relay that's out of date?

**Comment by metachris** [comment]
Reopened until confirmed

**Comment by Ruteri** [comment]
The version of `mev-boost` ran did not contain the fixes. Closing.
