### ISSUE TITLE
Only call `engine_getPayloadV1`  as fail over

### ISSUE THREAD

**Issue by terencechain** [flashbots/mev-boost#27]
`engine_getPayloadV1` gets requested to both relay and execution. Instead, I think we can save a request for a happy path and only call execution part of failing over

https://github.com/flashbots/mev-boost/blob/master/lib/service.go#L247

**Comment by jparyani** [comment]
Yep, this logic is a bit in flux, but you’re correct. Once we’ve added additional relays along with profit switching, we’ll only use the local execution as a fallback.

**Comment by metachris** [comment]
closing, with current spec there's no engine calls anymore
