### ISSUE TITLE
Invalid block from relayer - gas exceeding limit

### ISSUE THREAD

**Issue by wenye1024** [flashbots/mev-boost#271]
Hi everyone, my Goerli/Prater missed a block at Slot 3,748,745. I'm using Geth/Teku/Mevboost. Friends at Ethtaker says it's likely mev-boost proposed an invalid block but they are not 100% sure. Attached logs. And if someone can help me diagnose if the block from mev-boost was the issue. Thank you!
[error_logs.txt](https://github.com/flashbots/mev-boost/files/9434513/error_logs.txt)

**Comment by ralexstokes** [comment]
it does look like the flashbots builder provided a block that had the incorrect gas limit for the transactions given

**Comment by metachris** [comment]
Yep, the Goerli builder seems to have an issue, and the bad block went past the relay verification and was delivered. Thanks for the logs, they are very informative.

For reference, this is the bidtrace for the delivered block: https://builder-relay-goerli.flashbots.net/relay/v1/data/bidtraces/proposer_payload_delivered?slot=3748745

**Comment by metachris** [comment]
Updated the Goerli relay with additional verification, there was a short window with a debug mode enabled which let that block through the relay.
