### ISSUE TITLE
Allow setting a minimum bid value to determine whether or not to use a block supplied by the builder API

### ISSUE THREAD

**Issue by allboxes** [flashbots/mev-boost#273]
Currently users are required to make a binary choice between using a centralized block builder or forgoing MEV.

MEV-Boost should allow user's to set a fixed fee (e.g. 0.2 ETH) under which they will use a locally produced block.

In this way validators can gain exposure to large MEV opportunities while still contributing to decentralized block building when MEV is small/non existent.

Additionally, as the CL does not currently have a view into the value of a locally produced block, this provides some protection to user's from relay's producing very low value blocks.

In the future this can be enhanced by comparing the value of the locally built block vs. the remote builder's submission and using a fee delta instead of a fixed fee.

Originally submitted as an issue to a few CLs but it was suggested that it would be better to implement it in MEV-Boost.
https://github.com/ConsenSys/teku/issues/6140
https://github.com/sigp/lighthouse/issues/3517

**Comment by allboxes** [comment]
I took a stab at the PR, I have minimal GO experience but it seems to work fine.

**Comment by allboxes** [comment]
@metachris any thoughts on this?

**Comment by metachris** [comment]
Thanks for the contribution! And sorry for being slow to respond on this. It was on the radar, but due to the merge there were so many other priorities.

I wonder if there's an appetite for this feature from a wider audience. Could people please signify their interest by 👍 the initial comment above?

**Comment by allboxes** [comment]
> @allboxes, I think this PR is step in the right direction given that many people are wary of running mev-boost especially since the mev-boost reward has the possibility of being less than the reward you would have earned from a locally produced block. I have 2 comments (although this may be beyond the scope of the PR)

>    There are 2 types of min bid, absolute min bid and relative min bid. I take it this PR is an absolute mid bid, but it would also be useful to have the option to specify a relative min bid which would be the min bid above the reward you would receive from a locally produced block

>   Is there a way of transmitting this information to the relay? Under this implementation if I have a min bid of .1 eth will the relay realize this and only submit bids of .1 eth or more? Will the bid immediately be rejected, giving the relay the opportunity to submit a higher bid? Or will the low bid be silently ignored? The last case seems sub-optimal if the relay is willing to bid higher but did not know of the min required bid of the validator.

@jumboshrimp100, responding here to keep the PR clean.

The PR/issue is just for the absolute bid and this value is not exposed to the connected relays.  There is ongoing work on exposing the local block value to the CL so that the CL can compare between builder blocks and the local block.  If/when that functionality is implemented in the CLs/ELs it will make min-bid in MEV-Boost largely obsolete (unless there is desire to enable 2-way communication with the relays, which make or make not make sense given the complexity/game theory/additional latency concerns)

**Comment by metachris** [comment]
for reference, this is the EL APIs issue: https://github.com/ethereum/execution-apis/issues/307 about exposing the block value

**Comment by jtraglia** [comment]
@allboxes thanks for your contribution! It's a great feature.
