### ISSUE TITLE
Feature: Offer a portable build docker hub image

### ISSUE THREAD

**Issue by yorickdowne** [flashbots/mev-boost#275]
For users on older hardware that use docker, a portable docker image would be helpful. Maybe `latest-portable`?

**Comment by metachris** [comment]
good idea! it's already merged, we just need to release a new version. will do that today.

**Comment by metachris** [comment]
Done in v0.8.0: https://hub.docker.com/r/flashbots/mev-boost/tags

**Comment by metachris** [comment]
Could you verify that these work for you and report here?

**Comment by metachris** [comment]
Fixing the portable build here: https://github.com/flashbots/mev-boost/pull/282/files

**Comment by metachris** [comment]
fixed in v0.8.2: https://hub.docker.com/r/flashbots/mev-boost/tags 

could you confirm the portable images work for you as expected?

**Comment by yorickdowne** [comment]
Confirmed it works! Thank you guys!

**Comment by metachris** [comment]
Awesome, thanks!
