### ISSUE TITLE
Validate that parameters are hex

### ISSUE THREAD

**Issue by samczsun** [flashbots/mev-boost#278]
Just in case

https://github.com/flashbots/mev-boost/blob/c03c1674a19346ff6ff27c6c562f15b6d8d33f8a/server/service.go#L301

**Comment by jtraglia** [comment]
Hey @samczsun thanks for raising this concern. I believe this is already done.

The path for this handler is defined as the following, which guarantees hex values for `parent_hash` and `pubkey`:

https://github.com/flashbots/mev-boost/blob/7713bd9445dc817d75c506b63397662a792d1270/server/backend.go#L7

And in the handler function, both of those string lengths are validated:

https://github.com/flashbots/mev-boost/blob/7713bd9445dc817d75c506b63397662a792d1270/server/service.go#L305-L313
