### ISSUE TITLE
JSON deserialization DoS

### ISSUE THREAD

**Issue by samczsun** [flashbots/mev-boost#279]
If this is a concern, this needs to switch to using a decoder too

https://github.com/flashbots/mev-boost/blob/c03c1674a19346ff6ff27c6c562f15b6d8d33f8a/server/utils.go#L71

Also, a lot of types will deserialize a raw `[]bytes` which has limitless potential to DoS (although it will then result in an invalid message, so hey).

**Comment by jtraglia** [comment]
Hey @samczsun thanks but I'm not sure this should be a concern (at least not anymore).

If `SendHTTPRequest` returns an error, mev-boost won't crash (DoS) it will just log the error.

For example, when requesting headers (bids) from each relay:

https://github.com/flashbots/mev-boost/blob/7713bd9445dc817d75c506b63397662a792d1270/server/service.go#L328-L333

Additionally, these types have been fuzzed quite a bit. See this file:

https://github.com/flashbots/go-boost-utils/blob/main/types/builder_fuzz_test.go

How does this look to you?
