### ISSUE TITLE
Should we remove `engine_executePayloadV1`

### ISSUE THREAD

**Issue by terencechain** [flashbots/mev-boost#28]
`engine_executePayloadV1` is currently not used, should we just remove `engine_executePayloadV1` and `ExecutePayloadV1`?

**Comment by jparyani** [comment]
@thegostep any thoughts here? I know we had talked about this before, but I forget what the conclusion was.

**Comment by thegostep** [comment]
Yes - they can be removed. We will still want to proxy the requests to the execution clients, but it is not necessary for mev-boost logic.

**Comment by metachris** [comment]
done
