### ISSUE TITLE
mev-boost crash on startup on Windows x64 ?

### ISSUE THREAD

**Issue by nmoreau** [flashbots/mev-boost#284]
I am trying to run mev-boost on my staking machine on Win64 with go1.19 windows/amd64

I was able to pull the packagein from GitHub  compile the go package using 
`go install github.com/flashbots/mev-boost@latest`
I am using the[ TDM-GCC compiler ](https://jmeubank.github.io/tdm-gcc/articles/2021-05/10.3.0-release)

When I try to start mev-boost I got the following error below.
When running in docker from the latest docker image, I get a similar error.

Question : any recommendation or setup to run mev-boost on windows?

C:\Users\Nicolas>mev-boost -help
Exception 0xc000001d 0x0 0x0 0x7ff7b60849ee
PC=0x7ff7b60849ee
signal arrived during external code execution

runtime.cgocall(0x7ff7b60661b0, 0xc0000c7ba8)
        C:/Program Files/Go/src/runtime/cgocall.go:158 +0x4a fp=0xc0000c7b80 sp=0xc0000c7b48 pc=0x7ff7b5d9486a
github.com/supranational/blst/bindings/go._Cfunc_blst_sk_to_pk2_in_g1(0x0, 0xc0000862a0, 0xc0000a4da0)
        _cgo_gotypes.go:1317 +0x52 fp=0xc0000c7ba8 sp=0xc0000c7b80 pc=0x7ff7b600a0b2
github.com/supranational/blst/bindings/go.(*_Ctype_struct___4).From(...)
        C:/Users/Nicolas/go/pkg/mod/github.com/supranational/blst@v0.3.7/bindings/go/blst.go:219
github.com/flashbots/go-boost-utils/bls.PublicKeyFromSecretKey(...)
        C:/Users/Nicolas/go/pkg/mod/github.com/flashbots/go-boost-utils@v0.3.5/bls/bls.go:40
github.com/flashbots/mev-boost/server.init()
        C:/Users/Nicolas/go/pkg/mod/github.com/flashbots/mev-boost@v0.8.2/server/mock_relay.go:25 +0xec fp=0xc0000c7bf0 sp=0xc0000c7ba8 pc=0x7ff7b6063a2c
runtime.doInit(0x7ff7b609c940)
        C:/Program Files/Go/src/runtime/proc.go:6321 +0x12d fp=0xc0000c7d20 sp=0xc0000c7bf0 pc=0x7ff7b5dd7a4d
runtime.doInit(0x7ff7b609a9a0)
        C:/Program Files/Go/src/runtime/proc.go:6298 +0x71 fp=0xc0000c7e50 sp=0xc0000c7d20 pc=0x7ff7b5dd7991
runtime.doInit(0x7ff7b6095e80)
        C:/Program Files/Go/src/runtime/proc.go:6298 +0x71 fp=0xc0000c7f80 sp=0xc0000c7e50 pc=0x7ff7b5dd7991
runtime.main()
        C:/Program Files/Go/src/runtime/proc.go:233 +0x1bf fp=0xc0000c7fe0 sp=0xc0000c7f80 pc=0x7ff7b5dcae9f
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000c7fe8 sp=0xc0000c7fe0 pc=0x7ff7b5df5e01

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:363 +0xd6 fp=0xc000045fb0 sp=0xc000045f90 pc=0x7ff7b5dcb276
runtime.goparkunlock(...)
        C:/Program Files/Go/src/runtime/proc.go:369
runtime.forcegchelper()
        C:/Program Files/Go/src/runtime/proc.go:302 +0xb1 fp=0xc000045fe0 sp=0xc000045fb0 pc=0x7ff7b5dcb111
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000045fe8 sp=0xc000045fe0 pc=0x7ff7b5df5e01
created by runtime.init.6
        C:/Program Files/Go/src/runtime/proc.go:290 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:363 +0xd6 fp=0xc000047f90 sp=0xc000047f70 pc=0x7ff7b5dcb276
runtime.goparkunlock(...)
        C:/Program Files/Go/src/runtime/proc.go:369
runtime.bgsweep(0x0?)
        C:/Program Files/Go/src/runtime/mgcsweep.go:278 +0x8e fp=0xc000047fc8 sp=0xc000047f90 pc=0x7ff7b5db550e
runtime.gcenable.func1()
        C:/Program Files/Go/src/runtime/mgc.go:178 +0x26 fp=0xc000047fe0 sp=0xc000047fc8 pc=0x7ff7b5daa0a6
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000047fe8 sp=0xc000047fe0 pc=0x7ff7b5df5e01
created by runtime.gcenable
        C:/Program Files/Go/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc00001c070?, 0x7ff7b61f4f80?, 0x1?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:363 +0xd6 fp=0xc000057f70 sp=0xc000057f50 pc=0x7ff7b5dcb276
runtime.goparkunlock(...)
        C:/Program Files/Go/src/runtime/proc.go:369
runtime.(*scavengerState).park(0x7ff7b6398ce0)
        C:/Program Files/Go/src/runtime/mgcscavenge.go:389 +0x53 fp=0xc000057fa0 sp=0xc000057f70 pc=0x7ff7b5db3593
runtime.bgscavenge(0x0?)
        C:/Program Files/Go/src/runtime/mgcscavenge.go:617 +0x45 fp=0xc000057fc8 sp=0xc000057fa0 pc=0x7ff7b5db3b85
runtime.gcenable.func2()
        C:/Program Files/Go/src/runtime/mgc.go:179 +0x26 fp=0xc000057fe0 sp=0xc000057fc8 pc=0x7ff7b5daa046
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000057fe8 sp=0xc000057fe0 pc=0x7ff7b5df5e01
created by runtime.gcenable
        C:/Program Files/Go/src/runtime/mgc.go:179 +0xaa

goroutine 18 [finalizer wait]:
runtime.gopark(0x7ff7b6399420?, 0xc0000841a0?, 0x0?, 0x0?, 0xc000049f70?)
        C:/Program Files/Go/src/runtime/proc.go:363 +0xd6 fp=0xc000049e28 sp=0xc000049e08 pc=0x7ff7b5dcb276
runtime.goparkunlock(...)
        C:/Program Files/Go/src/runtime/proc.go:369
runtime.runfinq()
        C:/Program Files/Go/src/runtime/mfinal.go:180 +0x10f fp=0xc000049fe0 sp=0xc000049e28 pc=0x7ff7b5da91af
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000049fe8 sp=0xc000049fe0 pc=0x7ff7b5df5e01
created by runtime.createfing
        C:/Program Files/Go/src/runtime/mfinal.go:157 +0x45
rax     0x0
rbx     0x7ff7b638de80
rcx     0x7ff7b638d900
rdi     0xc25f1572e1a87b0e
rsi     0x7ff7b638de00
rbp     0x2b7cd71362065849
rsp     0xe8363fe4d8
r8      0x1f36a914d1d1ca54
r9      0xe3f09cc9f448ab2c
r10     0x53ae4ce3194e4adf
r11     0x988f6b1f351f9469
r12     0xf0030d9fa553ae92
r13     0x8e738258ad84f1f6
r14     0x685276af035ca2f
r15     0x0
rip     0x7ff7b60849ee
rflags  0x10246
cs      0x33
fs      0x53
gs      0x2b

**Comment by metachris** [comment]
What may help is using the portable build.

Please try either cloning the repo and building with `make build-portable`, or use one of the portable Docker images: https://hub.docker.com/r/flashbots/mev-boost

**Comment by nmoreau** [comment]
Thanks Chris, 
The docker portable build worked. Yeah! I am unblocked.

However the portable-build compilation failled.
The following commands in windows shell :
```
set CGO_CFLAGS=-"O -D__BLST_PORTABLE__"
go install github.com/flashbots/mev-boost@latest
```
fails on windows with the following error :

```
# runtime/cgo
gcc: error: unrecognized command-line option '-"O'; did you mean '-O'?
```
I am documenting this in case we want to get a comprehensive doc for solo stakers on Windows ;) - Diversity matters.

**Comment by metachris** [comment]
there was a bug in the makefile / CGO_FLAGS. the dash has to be inside the quotes, like this:

`set CGO_CFLAGS="-O -D__BLST_PORTABLE__"`

Updated the README in this PR: https://github.com/flashbots/mev-boost/pull/288

thanks for the report 🙏

**Comment by nmoreau** [comment]
This worked ! Thank you 🙏
