### ISSUE TITLE
The builder block fee receiving address has been changed

### ISSUE THREAD

**Issue by 2019jack** [flashbots/mev-boost#285]
# Lighthouse fee recipient set :

![image](https://user-images.githubusercontent.com/49616005/187822003-1d5bb036-66dd-43ab-978a-afc6194d2aea.png)

# mev-boost builder block:

time="2022-08-31T17:32:12Z" level=info msg="best bid" blockHash=0x28ee326e7f191fe840a3e27ef00149db9161b17552bf34195c13ca044edc8f81 blockNumber=7504419 method=getHeader module=service parentHash=0xc45f3b73f4cbffaf4152bed6aa19da27d30db1e91aeb03c53347cd98c11e0ce3 pubkey=0x852947a364193dcd3481013e2b31920b9ef35ecb2f5196b63da5140f586575481ec837b18fe0a551b68811e701487caa relays="https://0xafa4c6985aa049fb79dd37010438cfebeb0f2bd42b115b89dd678dab0670c1de38da0c4e9138c9290a398ecd9a0b3110@builder-relay-goerli.flashbots.net" slot=3788261 txRoot=0x5b318744de05c4cd762562e4a72151d722e412715880259de31e73688f25cca1 value=27517111615818308
time="2022-08-31T17:32:12Z" level=info msg="http: GET /eth/v1/builder/header/3788261/0xc45f3b73f4cbffaf4152bed6aa19da27d30db1e91aeb03c53347cd98c11e0ce3/0x852947a364193dcd3481013e2b31920b9ef35ecb2f5196b63da5140f586575481ec837b18fe0a551b68811e701487caa 200" duration=0.241650665 method=GET module=service path=/eth/v1/builder/header/3788261/0xc45f3b73f4cbffaf4152bed6aa19da27d30db1e91aeb03c53347cd98c11e0ce3/0x852947a364193dcd3481013e2b31920b9ef35ecb2f5196b63da5140f586575481ec837b18fe0a551b68811e701487caa status=200
time="2022-08-31T17:32:15Z" level=info msg="received payload from relay" blockHash=0x28ee326e7f191fe840a3e27ef00149db9161b17552bf34195c13ca044edc8f81 method=getPayload module=service url="https://builder-relay-goerli.flashbots.net/eth/v1/builder/blinded_blocks"

# https://goerli.etherscan.io/block/7504419

 @metachris  Looking at the link above, I am running lighthous to set the receiving fee address: 0x56dc1A196Aa187D913e431A61f6E7AeB7b85E6bB, but the mev-boost package block builder fee address is: 0xb64a30399f7f6b0c154c2e7af0a3ec7b0a5b131a, I have observed-2 days, is this mev-boost bug?

**Comment by 2019jack** [comment]
mev-boost version: mev-boost v0.7.10-10-g9168d4a

**Comment by metachris** [comment]
The block feeRecipient is Flashbot, and the proposer is paid with a payment transaction. In the block above it's this tx: https://goerli.etherscan.io/tx/0x8e3bfba60beb8d9d1eed220bdf28354ee7d64a2d54729b7ae619968c676f7046

That's the expected behavior.

**Comment by 2019jack** [comment]
got it! thanks. Can you charge Flashbots a percentage for block builders?
