### ISSUE TITLE
Set default `-request-timeout` to be consistent with `BUILDER_PROPOSAL_DELAY_TOLERANCE`

### ISSUE THREAD

**Issue by tbenr** [flashbots/mev-boost#287]
I think the mev-boost timeout toward the relays should be slightly less than what [consensus clients apply](https://github.com/ethereum/builder-specs/blob/main/specs/validator.md#constants) to mev-boost, to give some time to mev-boost to select the bid and respond within `1s`, otherwise the entire bid selection will be discarded and CL will fallback to local EL if one of the relays responds in >1s.

**Comment by metachris** [comment]
I wonder if we should add a different flag for registerValidator timeout, which is allowed to take longer. 

That would be useful in particular for anyone running many validators but having a bad internet connection. We have previously seen requests from India in particularly bad circumstances taking 2.5 seconds to transmit 1k validator registrations (which is only ~500kb).
