### ISSUE TITLE
How does the validator choose the relay?

### ISSUE THREAD

**Issue by Floristico** [flashbots/mev-boost#292]
Hi there, I have a question on how the validator chooses the relay:

So how does it work when you use multiple relays seperated with comma's. Does the validator use the first one by default and the second one as a backup or does it check all the relays for the highest payout?

**Comment by ralexstokes** [comment]
> does it check all the relays for the highest payout?

this, all configured relays will be queried in parallel and right now the highest bid by wei payment is selected to forward to the validator

**Comment by Floristico** [comment]
> > does it check all the relays for the highest payout?
> 
> this, all configured relays will be queried in parallel and right now the highest bid by wei payment is selected to forward to the validator

Thanks for answering👍 Does the validator automatically check itself if the proposed block is valid or does it trust the relayer? In other words, can i just add a bunch of relays or do I have to be careful?

**Comment by ralexstokes** [comment]
there are some things the validator could check and what is actually checked is client-dependent and I don't know the latest here for each client

there are some things the validator cannot check e.g. transaction validity and it trusts the relay to only allow valid transactions

you should be very careful about which relays you connect to and moreover should understand that things are still pretty early for the mev-boost ecosystem so there is a much higher chance of bugs etc which could mean loss of revenue as a validator

if you don't feel like you understand all of the risks I would try to learn more about them and hold off on running any external builder software until you know better what could happen
