### ISSUE TITLE
Request for inclusion in Node Operator Readiness list

### ISSUE THREAD

**Issue by chimera-defi** [flashbots/mev-boost#295]
Hi, 

1. I was wondering what the process is to get included in the Node operator readiness list here?
https://boost.flashbots.net/

We're running mev-boost at https://sharedstake.org on mainnet with 500 validators.  

Announcement:   
https://twitter.com/ChimeraDefi/status/1567100132864454657?s=20&t=jPGv94SEf89R3dJKAiPH7Q

Example registered validator:  
https://boost-relay.flashbots.net/relay/v1/data/validator_registration?pubkey=0x96093c4b3e770a44241eec0bb4cea6cce1d3311ef5a94ce7258929da155261ca04f5de2573acc5ca3bdd0746aee1248b

P.s. We've also open-sourced our setup scripts in case they're helpful for others, and allow setting up mev-boost with a single command (ideally)
https://github.com/chimera-defi/eth2-quickstart
Open to feedback too in case we made any mistakes.   

Thanks!

**Comment by kailinr** [comment]
hey @chimera-defi - thanks for filling out an issue w/ this request. We aren't actively adding _new_ node operator identifiers for testing anymore (since the Merge happens next week)! We can still add you if you are looking for visibility, but if you are already up and running there isn't really any immediate benefit to it anyway. Good job on this, and let us know!

**Comment by chimera-defi** [comment]
Hey @kailinr thanks for the reply! 
Would love to get added if it's not too much work! 
Figure y'all will need to update with the list of mev operators on mainnet anyway right? 
And our validators should be talking to the flashbots mev-boost relay, or you can call us out in case we messed up. 


I think adding us would be cool with the recent censorship and centralization concerns, considering we're:
- not US based
- offer a open rpc 
- open sourced quickstart scripts to help indie operators spin up their own nodes here 
https://github.com/chimera-defi/eth2-quickstart
Making it 1 of 3 publicly followable ways of setting up a node. 
- no VC funding, only community funding, not beholden to overreach based on where investors have money stashed...
- A top 10 ETH liquid staking pool https://defillama.com/protocols/liquid%20staking/Ethereum 
And it looks like yall got smaller pools, and far more centralized and un-audited pools in there already. 

> We can still add you if you are looking for visibility,

I apologize for not reaching out earlier since we didn't need "visibility" and didn't want it. 
But I'd love to work with y'all to help balance out that list since I'm running your software and wouldn't it be cool if more people ran it?

**Comment by kailinr** [comment]
hey @chimera-defi - just wanted to followup here that we are aligning on how much we can broadcast internally given the context shared. Will circle back :)

**Comment by metachris** [comment]
Added to boost.flashbots.net 👍

**Comment by chimera-defi** [comment]
Thanks @metachris !    
Thanks @kailinr!      

Really appreciate it!     
We also added the id you suggested and should be broadcasting at     
Thanks! Should be using it now w/ the uri  -  
 
https://0xac6e77dfe25ecd6110b8e780608cce0dab71fdd5ebea22a16c0205200f2f8e2e3ad3b71d3499c54ad14d6c21b41a37ae@boost-relay.flashbots.net?id=sharedstake
    
<3 keep up the great work
