### ISSUE TITLE
Warning - "Beacon node does not utilize a custom builder"

### ISSUE THREAD

**Issue by KomplexMojo** [flashbots/mev-boost#308]
Trying to get MEV-boost set up for the merge and I am getting the following warning.

level=warning msg="Beacon node does not utilize a custom builder via the --http-mev-relay flag. Validator registration skipped." prefix=validator

**Prysm Version 3.1.1
Geth Version 1.10.23**

MEV-Boost Service file:

ExecStart=/home/mev-boost/bin/mev-boost \
                -mainnet \
                -relay-check \
                -relays=https://0x8b5d2e73e2a3a55c6c87b8b6eb92e0149a125c852751db1422fa951e42a09b82c142c3ea98d0d9930b056a3bc9896b8f@bloxroute.max-profit.blxrbdn.com

====

Beaconchain Service file:

ExecStart=/usr/local/bin/beacon-chain \
  --mainnet \
  --datadir=/var/lib/prysm/beacon \
  --execution-endpoint=http://127.0.0.1:8551 \
  --jwt-secret=/eth1/var/lib/jwtsecret/jwt.hex \
  --suggested-fee-recipient=0x0000000000 \
  --checkpoint-sync-url=https://2DlhGQJdbqMolu4iFurHf7eTOSO:4edddff20107b04403aa63f944c79713@eth2-beacon-mainnet.infura.io \
  --genesis-beacon-api-url=https://2DlhGQJdbqMolu4iFurHf7eTOSO:4edddff20107b04403aa63f944c79713@eth2-beacon-mainnet.infura.io \
  --http-mev-relay=http://127.0.0.1:18550 \
  --accept-terms-of-use

===

**Comment by metachris** [comment]
seems to be an issue more suitable for the Prysm repository. ping @terencechain

**Comment by terencechain** [comment]
I suspect the relay endpoint is down at start up

@KomplexMojo can you restart and see if still persists? Can you also get me startup log as well? Feel free to dm me at Discord or telegram (@terencechain)
