### ISSUE TITLE
Allow more verbose logging of received payloads

### ISSUE THREAD

**Issue by tersec** [flashbots/mev-boost#311]
Even with https://github.com/flashbots/mev-boost/pull/309 it can be useful it can be useful to have a record of exactly what payload was not properly decoded, to determine whether it's a hitherto unspecified interoperability edge case between different assumptions of different JSON libraries or REST encoding/decodings.

**Comment by metachris** [comment]
done in #333

**Comment by metachris** [comment]
released in v1.3.2
