### ISSUE TITLE
Potentially allow mev-boost run even when check relays fails for one

### ISSUE THREAD

**Issue by dickmanben** [flashbots/mev-boost#312]
If validators are connecting to multiple relays and one goes down, should this stop mev-boost?

https://github.com/flashbots/mev-boost/blob/c5344c20eaab2c3b95d7b8652945a098e1367a87/server/service.go#L544

**Comment by metachris** [comment]
Only at startup, all relays need to be reachable, otherwise mev-boost doesn't start.

During running, it's only used for the getStatus request.

**Comment by metachris** [comment]
good point... sounds reasonable to just warn on startup, instead of fail completely.

**Comment by metachris** [comment]
Fixed in mev-boost v1.2.1: https://github.com/flashbots/mev-boost/releases/tag/v1.2.1
