### ISSUE TITLE
Port forwarding broken in `docker run` docs @ https://hub.docker.com/r/flashbots/mev-boost

### ISSUE THREAD

**Issue by analogue** [flashbots/mev-boost#314]
Since `mev-boost` defaults to listening on `localhost:18850`, the guidance provided @ https://hub.docker.com/r/flashbots/mev-boost fails in a surprising way since `mev-boost` needs to listen on `0.0.0.0:18550` for the `docker run ... -p 18550:18550` port forward to work correctly.

I'm guessing changing the default for `mev-boost` from `localhost:18550` to `0.0.0.0:18550` is probably not going to go over too well so the alternative is to simply update the documentation @ https://hub.docker.com/r/flashbots/mev-boost across all nets (mainnet, goerli, etc).

Broken docs:
```
docker run -p 18550:18550 flashbots/mev-boost:latest -mainnet -relay-check -relays https://0xac6e77dfe25ecd6110b8e780608cce0dab71fdd5ebea22a16c0205200f2f8e2e3ad3b71d3499c54ad14d6c21b41a37ae@boost-relay.flashbots.net
```

Fixed docs with `-addr` flag:
```
docker run -p 18550:18550 flashbots/mev-boost:latest -mainnet -addr 0.0.0.0:18550 -relay-check -relays https://0xac6e77dfe25ecd6110b8e780608cce0dab71fdd5ebea22a16c0205200f2f8e2e3ad3b71d3499c54ad14d6c21b41a37ae@boost-relay.flashbots.net
```

I would normally submit a PR, but I don't see the documentation in question under source control.

**Comment by metachris** [comment]
Thanks, updated the readme on Docker hub! 👍
