### ISSUE TITLE
Cannot connect to Builder

### ISSUE THREAD

**Issue by lucy-sha512** [flashbots/mev-boost#320]
Hi 
I am  running mev-boost client on goerli testnet with the following commands:
`sudo docker run flashbots/mev-boost -goerli  -relay-check -relays=https://0xafa4c6985aa049fb79dd37010438cfebeb0f2bd42b115b89dd678dab0670c1de38da0c4e9138c9290a398ecd9a0b3110@builder-relay-goerli.flashbots.net`

Iam  get the following  logs:
![mev](https://user-images.githubusercontent.com/26814150/190621425-693fb878-ad5a-460b-8d3e-40388d0b833e.png).

I am running my beacon node on goerli prater test net with the following commands:
`docker run -d -it -v /home/lucy/launch/prysm:/root -v /home/lucy/launch/geth/genesis.ssz:/genesis.ssz -v /home/lucy/launch/jwt.hex:/jwt.hex -p 4000:4000 -p 13000:13000 -p 12000:12000/udp --name beacon --net=host gcr.io/prysmaticlabs/prysm/beacon-chain:stable --datadir=/root --genesis-state=/genesis.ssz --accept-terms-of-use=true --rpc-host=0.0.0.0 --monitoring-host=0.0.0.0 --execution-endpoint=http://localhost:8551 --jwt-secret=/jwt.hex --suggested-fee-recipient=0x7Db8bD7FF6a856c1715a58BB4fd83BF43519bDa3 --http-mev-relay=http://localhost:18550  --prater`

I am getting the following error in the logs:

![beacon_error](https://user-images.githubusercontent.com/26814150/190622134-02d61100-59db-4fa9-a34a-4b8840a8f51f.png)

 **ERROR main: could not connect to builder: Get "http://localhost:18550/eth/v1/builder/status": dial tcp 127.0.0.1:18550: connect: connection refused**

**Comment by ralexstokes** [comment]
I believe you need to expose the port from the mev-boost container, otherwise the prysm container will not be able to access it

**Comment by metachris** [comment]
closing this issue. Thanks @ralexstokes  for providing the solution 🙏
