### ISSUE TITLE
`builder_getPayloadHeaderV1`  "unexpected end of JSON input"

### ISSUE THREAD

**Issue by terencechain** [flashbots/mev-boost#33]
Played with `builder_getPayloadHeaderV1` with the new relay endpoint, tried invalid payload ID as an experiment. Unfortunately, I don't think the error response is getting appropriately parsed as we are getting "unexpected end of JSON input."

```
./mev-boost -relayUrl https://relay-kintsugi.flashbots.net

curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"builder_getPayloadHeaderV1","params":["0x1"]}' http://localhost:18550

ERRO[0002] Could not parse response                      err="unexpected end of JSON input" method=engine_getPayloadV1 prefix=lib/service
```

**Comment by metachris** [comment]
Closing this since the APIs have changed significantly in the meantime. Please reopen if encountering this again :)
