### ISSUE TITLE
Requests to other relays are canceled as soon as one relay returns

### ISSUE THREAD

**Issue by kwood** [flashbots/mev-boost#330]
After proposing a block today, I saw the following messages:
```
level=info msg="best bid" blockHash=<REDACTED> blockNumber=<REDACTED> method=getHeader module=service parentHash=<REDACTED> pubkey=<REDACTED> relays="https://<REDACTED>@bloxroute.max-profit.blxrbdn.com" slot=<REDACTED>  txRoot=<REDACTED> value=<REDACTED> 
level=info msg="http: GET /eth/v1/builder/header/<REDACTED> /<REDACTED>/<REDACTED> 200" duration=0.180380465 method=GET module=service path=/eth/v1/builder/header/<REDACTED> /<REDACTED>/<REDACTED> status=200
level=info msg="received payload from relay" blockHash=<REDACTED> method=getPayload module=service url="https://bloxroute.max-profit.blxrbdn.com/eth/v1/builder/blinded_blocks"
level=error msg="error making request to relay" blockHash=<REDACTED> error="Post \"https://boost-relay.flashbots.net/eth/v1/builder/blinded_blocks\": context canceled" method=getPayload module=service url="https://boost-relay.flashbots.net/eth/v1/builder/blinded_blocks"
level=info msg="http: POST /eth/v1/builder/blinded_blocks 200" duration=0.185630197 method=POST module=service path=/eth/v1/builder/blinded_blocks status=200
```

Notably, the call to the flashbots relay was canceled, which would have returned a block with a larger reward than the bloxroute relay did.

Glancing at the code, it seems that the requests to the rest of the relays might be cancelled upon the first relay returning:
https://github.com/flashbots/mev-boost/blob/97207c6118778725f1703226f774e91e5395909d/server/service.go#L459

**Comment by metachris** [comment]
The flashbots relay could not have returned a block with a higher reward, because the proposer already sends the signed block header for which it wants to receive the payload.

mev-boost sends the payload to all the relays concurrently, and when it receives a payload, it cancels the other requests. That's what you see in the logs provided.

A different discussion could be about whether mev-boost should send the payload to all the relays. We originally added this for redundancy (as multiple relays might have produced the same block), but could be worth revisiting.

**Comment by schonex** [comment]
even if not revisiting, should this really be an 'error' if its by design? 

also why do all relays need to be send the payload if a best bidder has already been chosen?

**Comment by kwood** [comment]
Okay then, seems to be my misunderstanding.

I did check the slot on the flashbots relay, and there did seem to be a better block available in time, but hard to know what actually got delivered at the time.

Agree that if this is expected to happen every proposal with more than one relay configured, then the logging should be adjusted so that this isn't an error.

**Comment by metachris** [comment]
mev-boost asks all the relays for bids at the same time, and uses the best it receives. might be a builder submitted a better bid after your proposer asked for it, which is why you'd see it when checking manually after the fact.
