### ISSUE TITLE
Fee recipient from connected builder does not match, using it anyways

### ISSUE THREAD

**Issue by PixelNoob** [flashbots/mev-boost#336]
Fee recipient is changed when running mev boost, it seems builders can change the header and add different fee recipient which effectively steals the block tips and the mev fees as well.  

The message I get on lighthouse beacon client is:

`INFO Fee recipient from connected builder does not match, using it anyways., service: exec`

So far I have identified this probelm on goerli, this is the address of one known attacker: 0x9B3F8604D2F20a2F864Cd209e02c37e7C9997681

**Comment by ralexstokes** [comment]
this is an intended part of the design so that builders can in turn offer their blocks to others (e.g. searchers) who can simply pay a builder via payments using the `COINBASE` opcode. it is up to validators to only use relays working with builders who correctly pay the proposer

**Comment by PixelNoob** [comment]
> this is an intended part of the design so that builders can in turn offer their blocks to others (e.g. searchers) who can simply pay a builder via payments using the `COINBASE` opcode. it is up to validators to only use relays working with builders who correctly pay the proposer

Yes, the thing is the flashbot andthe bloXroute relay on goerli are both accepting builders who take validator's fees.. also isn't it a possibility that they will try this on mainnet?, switching addresses constantly will make it very hard for relays to ban this activities.

**Comment by metachris** [comment]
relays validate the blocks builders submit by simulating them, and guaranteeing that the proposers receive the promised payment in the transaction.

**Comment by PixelNoob** [comment]
> relays validate the blocks builders submit by simulating them, and guaranteeing that the proposers receive the promised payment in the transaction.

Good to know, its a shame flashbots is not doing this for goerli.

I will close this issue, thanks for the information.
