### ISSUE TITLE
Proposal: rename `main` branch to `develop`

### ISSUE THREAD

**Issue by metachris** [flashbots/mev-boost#357]
Like Prysm, to make it clear that it's not the latest stable release there. People looking for stable releases should checkout the latest tag, use go install or use the latest Docker image.

**Comment by metachris** [comment]
In addition, we could also consider having a stable branch with the state of the latest release.

**Comment by metachris** [comment]
we have a stable branch now, tracking the latest release

**Comment by come-maiz** [comment]
I like it, main + stable.

**Comment by metachris** [comment]
the thing is that `main` is not necessarily as stable as it implies, PRs could be merged without exhaustive tests having run. These would only run before a new release.

Which is why I'd like to rename the `main` branch to `develop`, to make it more explicit that using it is maybe using an experimental version.

**Comment by ralexstokes** [comment]
I'd support this, either following prysm's lead or lighthouse with `stable`/`unstable`

**Comment by terencechain** [comment]
+1

**Comment by metachris** [comment]
Created `develop` branch, set it as repository default branch, and removed `main` branch.
