### ISSUE TITLE
Prysm context deadline exceeded, falling back to building block locally

### ISSUE THREAD

**Issue by Chaz27** [flashbots/mev-boost#359]
I'm having an issue with prysm timing out while trying to build a block via mev-boost. I have an issue open on their git as well (https://github.com/prysmaticlabs/prysm/issues/11490) hoping for advice here if there is anything I'm missing.

Prysm is successfully registering the validator and calling the get header function, but is timing out on the response and falling back to building the block locally. There's a hard 1 second timeout that's not configurable from the specs as I understand. However I did find that the getheader function in mev-boost can be configured. So I changed that from 950ms to 700ms as a bit of a test. The response did indeed return within 700ms, but prysm still timed out. I can see the timestamp in the logs on prysm and mev-boost are all happening with the same second. I'm a bit stumped as to what is happening.

**Comment by metachris** [comment]
Could you please provide the full logs of both mev-boost and Prysm?
