### ISSUE TITLE
add support for kiln

### ISSUE THREAD

**Issue by thegostep** [flashbots/mev-boost#36]
The latest release of the pos Ethereum spec is called "Kiln" and will be used as the new testnet. The full spec can be referenced here: https://hackmd.io/@n0ble/kiln-spec

The following work needs to take place in order to be up to date with this release:
- update mev-boost specs to reference the latest engine API: https://github.com/ethereum/execution-apis/blob/v1.0.0-alpha.7/src/engine/specification.md
- `engine_executePayloadV1 ` was renamed to `engine_newPayloadV1` and the behavior was modified. This has implications for the fraud proof mechanism of milestone 2 as it is unclear if mev-boost can rely on this API to perform historical payload simulation. The POS research team and implementation teams should be contacted to address this issue.

**Comment by metachris** [comment]
See
* https://github.com/flashbots/mev-boost/pull/47
* https://github.com/flashbots/mergemock/compare/master...flashbots:kiln

**Comment by jparyani** [comment]
Done in #47
