### ISSUE TITLE
Validator failed to sign block

### ISSUE THREAD

**Issue by danspina1** [flashbots/mev-boost#364]
Hi, 

Two of our validators have failed to sign blocks using MEV.

Logs from our validator 
`time="2022-09-28 08:04:00" level=error msg="Failed to propose block" error="rpc error: code = Unknown desc = error posting the SignedBlindedBeaconBlockBellatrix to the builder api: unsupported error code: 502: did not receive 200 response from API" prefix=validator pubKey=0x86677a495cea`

Logs from mev-boost 

`time="2022-09-28T08:04:00Z" level=error msg="error making request to relay" blockHash=0x2523ce4eb3ef36da80913668261ef0ca78f3724e344f227f8033a1caa39e8e37 error="HTTP error response: 400 / {\"code\":400,\"message\":\"read tcp 10.21.31.0:8080-\\u003e10.21.23.74:11262: i/o timeout\"}\n" method=getPayload module=service parentHash=0x4ae7bb29df0d77a3633144d63684650fe9ee14da79c3ef9e1b76a834b428b0c5 slot=4794018 url="https://boost-relay.flashbots.net/eth/v1/builder/blinded_blocks"
time="2022-09-28T08:04:00Z" level=error msg="no payload received from relay -- could be a network error or withholding." blockHash=0x2523ce4eb3ef36da80913668261ef0ca78f3724e344f227f8033a1caa39e8e37 method=getPayload module=service parentHash=0x4ae7bb29df0d77a3633144d63684650fe9ee14da79c3ef9e1b76a834b428b0c5 relays="https://0xac6e77dfe25ecd6110b8e780608cce0dab71fdd5ebea22a16c0205200f2f8e2e3ad3b71d3499c54ad14d6c21b41a37ae@boost-relay.flashbots.net/" slot=4794018
time="2022-09-28T08:04:00Z" level=info msg="http: POST /eth/v1/builder/blinded_blocks 502" duration=1.078647788 method=POST module=service path=/eth/v1/builder/blinded_blocks status=502`

**Comment by metachris** [comment]
It looks like the reason was an internal networking problem between the ingress and the API.
