### ISSUE TITLE
remove use of engine_getPayloadV1 from mev-boost

### ISSUE THREAD

**Issue by thegostep** [flashbots/mev-boost#37]
Some consensus clients have expressed the desire of implementing the mev-boost logic as a module to the consensus client directly. This would generally be good for security as it would provide greater diversity in implementation, but it may also make it more difficult to publish updates to mev-boost in the future. My recommendation would be to continue down the path of using mev-boost as a canonical implementation, but acknowledge this future direction.

One architecture level change which can be implemented now is the removal of the use of `engine_getPayloadV1` from the block proposal process. This can be done because consensus clients are expected to fallback to a local execution client only if no payloads are returned from relays.

This change requires updating the specs, updating the mev-boost implementation and notifying client implementation teams.

**Comment by metachris** [comment]
closing, as this change has already been formalised. if needed we could open a new issue for a specific action item.
