### ISSUE TITLE
Allow validator specified list of blocked addresses to be shared with relay upon registration

### ISSUE THREAD

**Issue by dickmanben** [flashbots/mev-boost#378]
Censorship is no one's favorite topic here but we all know that different validators and companies require compliance with the governmental bodies they operate under.  Because of this compliance there are multiple relays that provide regulation in the blocks they provide to validators.  Currently validators using mev-boost connect to a relay that will provide censorship to the level that the relay is required to, though this may be out of date or could be less strict than the regulation that a validator is required to follow.

___

Proposal is to allow mev-boost to provide a list of addresses which user's specify is require to be excluded from any blocks sent to them.  Relays and builders can then provide the service to these validators in a way that honors any requirement they have regarding censorship.

This can also improve the relationship between relays and builders to have more successful submissions that honor the regulation required by the relay and the validator.

My hope is that in doing so there can be relays where validators specify the level of regulation they need, if any at all, allowing the validator to be in more control of their censorship.

This change wouldn't impact relays that provide no censorship at all but would improve the quality of regulated relays as well as allow other relays to honor what the validator wants to do.

**Comment by metachris** [comment]
I think the correct place for this discussion would be https://github.com/ethereum/builder-specs.

The Flashbots forum might also be a place to get feedback: https://collective.flashbots.net
