### ISSUE TITLE
Changes for Capella and EIP-4844

### ISSUE THREAD

**Issue by metachris** [flashbots/mev-boost#392]
[Capella](https://github.com/ethereum/consensus-specs/blob/dev/specs/capella/beacon-chain.md#extended-containers) and [EIP-4844](https://www.eip4844.com/) will require changes to mev-boost, builder-specs, relay and builders.

* Both introduce new fields to `BeaconBlockBody`, `ExecutionPayload` and `ExecutionPayloadHeader`: [eip4844](https://github.com/ethereum/consensus-specs/blob/dev/specs/eip4844/beacon-chain.md#extended-containers) / [capella](https://github.com/ethereum/consensus-specs/blob/dev/specs/capella/beacon-chain.md#extended-containers) 
* This will break previous SSZ encoding/decoding (and strict JSON too), and needs a mev-boost update alongside EL+CL updates.
* MEV-Boost will need to know about multiple container versions and handle the forks correctly

### Capella

* update types in mev-boost to know about both [bellatrix](https://github.com/attestantio/go-eth2-client/tree/master/spec/bellatrix) and [capella](https://github.com/attestantio/go-eth2-client/tree/master/spec/capella) containers
* on getPayload, mev-boost detects whether payload is Capella or Bellatrix format and handles it correctly

### EIP-4844
* changes TBD
* "For the relayer side, there's more work, they probably want to verify blobs, the commitments, and the version hashes are valid. Those will be coming from the builders" (@terencechain)

**Comment by metachris** [comment]
We may also want to revert https://github.com/flashbots/mev-boost/pull/299 now, since it would incorrectly alert to have received a different block hash once the new payload fields are live.

**Comment by metachris** [comment]
Related effort - using types from Attestant to reduce maintenance overhead:

* #404 
* #411

**Comment by metachris** [comment]
## Capella

<p><strong>Notes</strong></p>
<ul>
<li>enables withdrawals</li>
<li><a href="https://github.com/ethereum/consensus-specs/tree/dev/specs/capella"><a href="https://github.com/ethereum/consensus-specs/tree/dev/specs/capella">https://github.com/ethereum/consensus-specs/tree/dev/specs/capella</a></a></li>
<li><a href="https://github.com/ethereum/consensus-specs/blob/dev/specs/capella/beacon-chain.md"><a href="https://github.com/ethereum/consensus-specs/blob/dev/specs/capella/beacon-chain.md">https://github.com/ethereum/consensus-specs/blob/dev/specs/capella/beacon-chain.md</a></a></li>
</ul>

<p><strong>Payload changes</strong></p>

* https://github.com/ethereum/consensus-specs/blob/dev/specs/capella/beacon-chain.md#extended-containers



| Container | Change
| -- | --
| `ExecutionPayload` | new field: `withdrawals: List[Withdrawal, MAX_WITHDRAWALS_PER_PAYLOAD]`  # [New in Capella]
| `ExecutionPayloadHeader` | new field: `withdrawals_root: Root` # [New in Capella]
| `BeaconBlockBody` | new field: `bls_to_execution_changes: List[SignedBLSToExecutionChange, MAX_BLS_TO_EXECUTION_CHANGES]` # [New in Capella]
| `SignedBLSToExecutionChange` | (new container)
| `BLSToExecutionChange` | (new container)
| `Withdrawal` | (new container)

**Comment by jimmygchen** [comment]
Hi @metachris 
@0xGabi and I are working on builder spec changes for EIP-4844, will link the PR here we've pushed the changes!

**Comment by jimmygchen** [comment]
We've created a draft PR on builder spec here here: https://github.com/ethereum/builder-specs/pull/58

**Comment by metachris** [comment]
Closed in favor of https://github.com/flashbots/mev-boost/issues/451
