### ISSUE TITLE
Relayer profitability? 

### ISSUE THREAD

**Issue by AustinFoss** [flashbots/mev-boost#399]
Hello! I was redirected here from the FAQ section here: https://github.com/flashbots/mev-boost/wiki/Frequently-Asked-Questions

I'm just having a hard time mapping out how each link in the new PBS model (searchers, builders, & relayers) profit? Asked another way, what each's economic incentive to participate and run the service?

It's my understanding that builders build the most profitable block for the validator, and collect a fee for themselves but am little lost as to how relays and searchers are incentivized to participate?

**Comment by ralexstokes** [comment]
I'd consider builders as just another type of searcher and their revenue model is the same: for some kind of (order, bundle) flow, the actor (searcher, builder) tries to make the most profitable object and suggests they take a fee for themselves from the materialized value; in a competitive market, you have many agents competing over opportunities so this fee becomes some small margin on top of costs (assuming no other cash flowing activities, a big assumption!) and most of the value in a given opportunity flows elsewhere in the "value chain" (today, we see most mev profits flowing to validators actually)

relayers are a critical part of today's blockspace market and you could expect them to do something similar to monetize -- although in fact to my knowledge none of the relays take any fee for their services; some relays basically "bundle" a builder and so you can imagine the two just operating together and the relay costs factoring into just another line item for the builder's costs. other relays are operated "at a loss" as they are seen by their providers as public goods to bootstrap the PBS ecosystem -- it remains to be seen if we will get any relays in the picture that do in fact monetize; I generally think it would be good as it signals relaying itself can be a profitable business and that would encourage greater competition (in a place that given today's constraints of the PBS model needs it the most!)

**Comment by AustinFoss** [comment]
Thank you very much for the very informative reply!
