### ISSUE TITLE
finalize and merge milestone 1 and 2 specs

### ISSUE THREAD

**Issue by thegostep** [flashbots/mev-boost#40]
The specs should be merged in order to provide client teams with a stable api to build against. Once merged, it will be necessary to work with the consensus client teams to add compatibility.

<img width="555" alt="image" src="https://user-images.githubusercontent.com/15959632/155396890-9e57c9f3-ecfd-490c-88e2-aa2c9ebcac08.png">

**Comment by metachris** [comment]
Closing this issue, because there's no additional todos / action items from this one. Any remaining tasks should be added/referenced in #89
