### ISSUE TITLE
Proposal: replace types from go-boost-utils with types from Attestant

### ISSUE THREAD

**Issue by metachris** [flashbots/mev-boost#404]
Attestant / @mcdee has been working on up-to-date types with a lot of tests: https://github.com/attestantio/go-eth2-client/tree/master/spec

I'm proposing to switch to the attestandtio types and deprecate the go-boost-utils types.

This would be one less thing to worry about, and one less repository to maintain.

**Comment by ralexstokes** [comment]
this works for me, the key things to consider are:

1. ssz library used
2. maintainability, reliability of implementation

and it looks like both sources use the same ssz library so (1) is no change and I have no concerns personally about (2)

**Comment by prestonvanloon** [comment]
We mentioned this in the Prysm release today. More context can be found here: https://github.com/prysmaticlabs/prysm/issues/11717

**Comment by metachris** [comment]
work is underway, closing this for now.
