### ISSUE TITLE
feature-request: Ask a second relay for the payload, if the winner relay did not provide payload in time

### ISSUE THREAD

**Issue by biteric2000** [flashbots/mev-boost#405]
Previously, there has been several times when a mev relay who won the bid but did not provide the payload in time (either connection issue or a service issue), resulting in missed proposals and loss of money.

In future, is it possible that we could ask a second relay for the payload as a backup simultaneously? Or ask in sequence when the first relay fails to respond and then ask a second best bid?

---------
Examples of the missed proposals due to not getting payload from best bidder in time:

...
time="2022-11-02T..." level=info msg="best bid" blockHash=0x2433c38afa8ae9770a7aaf07176b135b270b6a5d6af3747fc06d52d05b9f4dad blockNumber=xxx method=getHeader module=service parentHash=xxx pubkey=xxx relays="https://0xb3ee7afcf27f1f1259ac1787876318c6584ee353097a50ed84f51a1f21a323b3736f271a895c7ce918c038e4265918be@relay.edennetwork.io" slot=xxx txRoot=0xf41a6dbbc4e5a49105148422c206975f60580221582e5f785472049132527308 value=97027507961221801 version=1.3.2
time="2022-11-02T..." level=info msg="http: GET /eth/v1/builder/header/xxx/xxx/xxx 200" duration=0.649754 method=GET module=service path=/eth/v1/builder/header/xxx/xxx/xxx status=200
time="2022-11-02T..." level=error msg="error making request to relay" blockHash=0x2433c38afa8ae9770a7aaf07176b135b270b6a5d6af3747fc06d52d05b9f4dad error="Post \"https://relay.edennetwork.io/eth/v1/builder/blinded_blocks\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" method=getPayload module=service parentHash=xxx slot=xxx url="https://relay.edennetwork.io/eth/v1/builder/blinded_blocks" version=1.3.2
time="2022-11-02T..." level=error msg="no payload received from relay!" blockHash=0x2433c38afa8ae9770a7aaf07176b135b270b6a5d6af3747fc06d52d05b9f4dad method=getPayload module=service parentHash=xxx relays="https://0xb3ee7afcf27f1f1259ac1787876318c6584ee353097a50ed84f51a1f21a323b3736f271a895c7ce918c038e426

...
time="2022-10-17T..." level=info msg="best bid" blockHash=0x6fab46a948a6cd834aa7eaa5dc244cb3102c3ab5e3ca0b6058839c1fda53ca8c blockNumber=xxx method=getHeader module=service parentHash=xxx pubkey=xxx relays="https://0xb3ee7afcf27f1f1259ac1787876318c6584ee353097a50ed84f51a1f21a323b3736f271a895c7ce918c038e4265918be@relay.edennetwork.io" slot=xxx txRoot=0x758a300d635146604d935fb5db3dc7f1a56120632f70760f466523753e90df14 value=74472431003129321 version=1.3.2
time="2022-10-17T..." level=info msg="http: GET /eth/v1/builder/header/xxx/xxx/0xxxx 200" duration=0.963004 method=GET module=service path=/eth/v1/builder/header/xxx/xxx/0xxxx status=200
time="2022-10-17T..." level=debug msg=getPayload method=getPayload module=service version=1.3.2
time="2022-10-17T..." level=debug msg="calling getPayload" blockHash=0x6fab46a948a6cd834aa7eaa5dc244cb3102c3ab5e3ca0b6058839c1fda53ca8c method=getPayload module=service parentHash=xxx slot=xxx url="https://relay.edennetwork.io/eth/v1/builder/blinded_blocks" version=1.3.2
time="2022-10-17T..." level=error msg="error making request to relay" blockHash=0x6fab46a948a6cd834aa7eaa5dc244cb3102c3ab5e3ca0b6058839c1fda53ca8c error="HTTP error response: 400 / {\"code\":400,\"message\":\"read tcp 10.44.20.16:9062-\\u003e130.211.0.83:53390: i/o timeout\"}\n" method=getPayload module=service parentHash=xxx slot=xxx url="https://relay.edennetwork.io/eth/v1/builder/blinded_blocks" version=1.3.2
time="2022-10-17T..." level=error msg="no payload received from relay!" blockHash=0x6fab46a948a6cd834aa7eaa5dc244cb3102c3ab5e3ca0b6058839c1fda53ca8c method=getPayload module=service parentHash=xxx relays="https://0xb3ee7afcf27f1f1259ac1787876318c6584ee353097a50ed84f51a1f21a323b3736f271a895c7ce918c038e4265918be@relay.edennetwork.io" slot=xxx version=1.3.2

Note: The relays are working as intended 99% of the time, but things like the above just happens.

**Comment by jtraglia** [comment]
Hey @biteric2000 that's a great suggestion, but unfortunately it's not possible. At this particular moment, you have submitted a `SignedBlindedBeaconBlock` to the relay and would be at risk of being slashed if you proposed a different block as a fallback. The relay could gossip the block you sent it and you would be slashed for making two proposals.

According to the [builder-specs](https://github.com/ethereum/builder-specs/blob/main/specs/validator.md#proposer-slashing):

> This means if a validator publishes a signature for a `BlindedBeaconBlock` (via a dissemination of a `SignedBlindedBeaconBlock`) then the validator **MUST** not use the local build process as a fallback, even in the event of some failure with the external builder network.

In your examples, both of the missing payloads came from the Eden relay. I suggest reaching out to them.

**Comment by biteric2000** [comment]
Thank you @jtraglia for your helpful comment and explanation.
The above logs are just examples. Actually we just missed one proposal with relaywooor yesterday, with a reward tip of 0.08 ETH lost (excluding execution reward). Previously we also tried to contact the relay service providers through channels like discord, but with little feedback / solution.
Anyway, looking forward to any possible means towards solving the similar problems in future!
