### ISSUE TITLE
error calling registerValidator on relay, failed to verify validator signature

### ISSUE THREAD

**Issue by nivshitrit** [flashbots/mev-boost#415]
we just activated a validator on mainnet today, and im getting this error in my mev container. on testnet it was working just fine, but im getting errors in my mev container.

flags : 
--addr=0.0.0.0:18550
--relay-check
--mainnet
--relay=https://0xac6e77dfe25ecd6110b8e780608cce0dab71fdd5ebea22a16c0205200f2f8e2e3ad3b71d3499c54ad14d6c21b41a37ae@boost-relay.flashbots.net

error in mev-boost container:

**level=warning msg="error calling registerValidator on relay" error="HTTP error response: 400 / {\"code\":400,\"message\":\"failed to verify validator signature for 0x81fa53042ab95f1bd56e733d966d42f3340f062ca330cc1b2a67acfe79d06bceda6d5f37c3995b0b29510ba7d3a366c0\"}\n" method=registerValidator numRegistrations=1 ua=Go-http-client/1.1 url="https://boost-relay.flashbots.net/eth/v1/builder/validators" version=v1.4.0**

**level=info msg="http: POST /eth/v1/builder/validators 502" duration=0.312082 method=POST path=/eth/v1/builder/validators status=502 version=v1.4.0**

other than the error, everything mostly seems ok:

**_time="2022-11-17T15:40:10Z" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.136784 method=GET path=/eth/v1/builder/status status=200 version=v1.4.0
time="2022-11-17T15:41:10Z" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.140290 method=GET path=/eth/v1/builder/status status=200 version=v1.4.0
time="2022-11-17T15:42:10Z" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.166274 method=GET path=/eth/v1/builder/status status=200 version=v1.4.0
time="2022-11-17T15:43:10Z" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.149643 method=GET path=/eth/v1/builder/status status=200 version=v1.4.0
time="2022-11-17T15:44:10Z" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.140354 method=GET path=/eth/v1/builder/status status=200 version=v1.4.0_**

**Comment by metachris** [comment]
Please double-check that you are using mainnet validator configuration with your validator client.

**Comment by nivshitrit** [comment]
Wow, i was indeed running my validator with -goerli flag, cant believe i didnt notice that, glad that my validator was still attesting as normal this whole time.

i removed the flag and now the error is gone, thanks
