### ISSUE TITLE
Broken link in MEV-Boost Quickstart

### ISSUE THREAD

**Issue by JustinDrake** [flashbots/mev-boost#418]
One of the links in the quickstart section of https://boost.flashbots.net is broken.

The "supported consensus client" link (see screenshot below) is to https://boost.flashbots.net/#block-356364ebd7cc424fb524428ed0134b21, which doesn't do anything.

<img width="343" alt="Screenshot 2022-11-19 at 14 29 09" src="https://user-images.githubusercontent.com/731743/202855790-22dbaa15-57d3-4018-b55d-ad69178a6ddb.png">

**Comment by metachris** [comment]
thanks, updated 🙏
