### ISSUE TITLE
Allow operating a builder with no fee and no payout TX

### ISSUE THREAD

**Issue by krasi-georgiev** [flashbots/mev-boost#419]
# Rationale

Why should this feature exist?
 - when the builder doesn't collect any fee it is very enificient to create a payout TX on every block.
some validators use a contract which consumes 70-100k gas so without the payout TX the total block value will be  higher.

What are the use-cases?
 - operating a builder that doesn't collect block fees.

# Implementation

Do you have ideas regarding the implementation of this feature?
 - yes
   the simulation checks - 
 	- if the coinbase address is the same as the validator's address 
 	- the coinbase balance difference is the same as the bid value

Are you willing to implement this feature?
 - yes
 
 cc @Ruteri

**Comment by krasi-georgiev** [comment]
Why does it matter that there could be other transfers to the coinbase?

The best block is the one that pays the most to the validator so even if there are other payments to the coinbase these are ok to assume as a reward.

The builder code does exactly that, just checks the coinbase balance before and after regardless of how the difference is accumulated.

**Comment by krasi-georgiev** [comment]
ping @metachris

**Comment by metachris** [comment]
Some builders are already doing this, by setting the proposer feeRecipient as coinbase address. Discussions about the block scoring and payment standardisation are happening in https://collective.flashbots.net/t/block-scoring-for-mev-boost-relays/202

I'm not quite sure what exactly you'd like to change?

**Comment by krasi-georgiev** [comment]
the flashbot relay rejects blocks without a payout TX

**Comment by krasi-georgiev** [comment]
@metachris I looked at the relay implementation and there is no way to avoid having a payout by setting up proposer feeRecipient as coinbase address, It runs a check to ensure that the last TX is a payout TX.
A requirement to have a payout TX complicated a few things and is really just inefficient.

For tracking purposes, this can be enforced using other methods.
