### ISSUE TITLE
latest-portable out of date

### ISSUE THREAD

**Issue by dc25** [flashbots/mev-boost#421]
latest-portable was last pushed 2 months ago so it looks like it has not been updated to 1.4.0-portable.   Actually using it confirms this - new command line option is missing from latest-portable.

**Comment by metachris** [comment]
Thanks for the heads-up! Will be looking into it.

In the meantime, nowadays (i think since v1.4.0) the regular `:latest` image is the portable build.

**Comment by metachris** [comment]
See also https://github.com/flashbots/mev-boost/issues/422

**Comment by metachris** [comment]
resolved, `latest-portable` is no longer available, and the `latest` image on docker hub is a portable build
