### ISSUE TITLE
getPaylaod default timeout

### ISSUE THREAD

**Issue by dmarzzz** [flashbots/mev-boost#428]
The hardcoded timeout on getPayload is defaulted at 4 seconds for MEV-boost but some consensus clients, such as [Prysm](https://github.com/prysmaticlabs/prysm/pull/11413) and Teku, are defaulting to 3 seconds. Should we try to align these or are there other reasons they are/should be different?

**Comment by ralexstokes** [comment]
at this stage in the process, the relay will either return the payload or not

if they are not able to do so in a small number of seconds, something is probably up; the exact number could be measured if we had delivery metrics across all relays and say "how long does it take for 99% of payloads to arrive?"

I would think in practice this number of actually much smaller than 3-4 seconds so we could be far more aggressive with the timeout

that being said, if the payload is not released it means a liveness failure for the chain so it is worth waiting for an excessive amount of time

-- do the timeouts need to be synchronized? it may be nice but I don't really see the need to do so other than some unnecessary resource consumption by mev-boost while it is waiting the extra second

**Comment by dmarzzz** [comment]
ah great point! Leaving the timeout higher gives us more information, i.e. maybe the payload wasn't sent in 3s, but it was sent in say 3.5s as opposed to never being sent at all. And as you mention it doesn't matter to the validator what it is. 

In terms of lowering the default, I think incentives take care of natural downward pressure on return time here and max wiggle room is good for unexpected circumstances.

**Comment by dmarzzz** [comment]
ah great point! Leaving the timeout higher gives us more information, i.e. maybe the payload wasn't sent in 3s, but it was sent in say 3.5s as opposed to never being sent at all. And as you mention it doesn't matter to the validator what it is. 

In terms of lowering the default, I think incentives take care of natural downward pressure on return time here and max wiggle room is good for unexpected circumstances.

**Comment by dmarzzz** [comment]
closing this issue as its not really an issue
