### ISSUE TITLE
Expose the time when the validator requested the payloud

### ISSUE THREAD

**Issue by krasi-georgiev** [flashbots/mev-boost#432]
It would be beneficial if the payload delivered exposes the time it was requested. Useful for estimating the latency between the submit and the requests 
https://boost-relay.flashbots.net/relay/v1/data/bidtraces/proposer_payload_delivered?block_number=...

**Comment by metachris** [comment]
Could you add a proposed API at the relay specs please? https://github.com/flashbots/relay-specs

**Comment by krasi-georgiev** [comment]
https://github.com/flashbots/relay-specs/issues/8
