### ISSUE TITLE
Add an api to query if a given builder is in the low or high priority queue

### ISSUE THREAD

**Issue by krasi-georgiev** [flashbots/mev-boost#433]

**Comment by metachris** [comment]
please open that issue on the relay repo: https://github.com/flashbots/mev-boost-relay

**Comment by metachris** [comment]
or even better, at the relay-specs: https://github.com/flashbots/relay-specs

**Comment by metachris** [comment]
makes sense, btw

**Comment by krasi-georgiev** [comment]
https://github.com/flashbots/relay-specs/issues/9
