### ISSUE TITLE
Feature Request: allow specifying minimum priority fee.

### ISSUE THREAD

**Issue by jhoenicke** [flashbots/mev-boost#471]
I noticed that recently people start setting the priority fee to 0.1 Gwei or even 1 wei. The current incentives make this possible, because validators choose the most profitable block without even knowing how big this block will be and block builders don't care so much. 

Given that a larger block has a bigger chance to be orphaned, the additional orphan risk is probably not worth the few microcent that a full block of 1wei transactions would pay to the validator.

It would be nice if a validator could specify in addition to the payout address and gas target also a minimum priority fee.  Instead of simply choosing the block with the largest fee, a validator would subtract `minimum fee*gas usage` before comparing the fees.  This would also require block builders to reveal gas usage in addition to paid fee.

**Comment by metachris** [comment]
MEV-Boost does not inspect transactions, and could not enable that. It could only help passing that message to the relay, in which case it'd require a spec change in https://github.com/ethereum/builder-specs/

If you want to pursue this, please open an issue in https://github.com/ethereum/builder-specs/ for further discussion 🙏

**Comment by ralexstokes** [comment]
also worth noting that in a mature builder market, builders are also highly incentivized to avoid orphan risk themselves so to the extent the builder market is competitive, validators don't really need to worry about this
