### ISSUE TITLE
Replace blst with pure Go bls12-381 library

### ISSUE THREAD

**Issue by jtraglia** [flashbots/mev-boost#478]
Using a pure Go library for signature verification would
* simplify the build process,
* make all builds portable, and
* remove our dependence on CGo.

Two potential options:

* [kilic/bls12-381](https://github.com/kilic/bls12-381)
* [bls12381](https://github.com/ethereum/go-ethereum/tree/bba2a1bac5fb896e644ff6a5307419812e0f6819/crypto/bls12381) in Geth

**Comment by metachris** [comment]
testing in #479
