### ISSUE TITLE
discussion: switch logging to go-ethereum/log

### ISSUE THREAD

**Issue by metachris** [flashbots/mev-boost#48]
Pros:

* `go-ethereum/log` seems to be the standard around Ethereum related projects
* also used by mergemock, and various Flashbots projects
* it has pretty much the same features as `logrus`
* we already use `go-ethereum` as dependency, and we could simply remove the `logrus` dependency

wdyt?

**Comment by elopio** [comment]
Prysm uses logrus, right @terencechain?

I wonder if you have any recommendations here.

I'm not sure this fork gives me confidence: https://github.com/ethereum/go-ethereum/blob/master/log/README_ETHEREUM.md

**Comment by terencechain** [comment]
Indeed. Prysm uses `logrus`, it's well supported, and it has all the functionality we need. `go-ethereum/log` is also great. I don't have a strong opinion here

**Comment by metachris** [comment]
Let's keep logrus :)
