### ISSUE TITLE
Release 1.5.0 checksum discrepency

### ISSUE THREAD

**Issue by TJGreen97** [flashbots/mev-boost#481]
The `mev-boost_1.5.0_linux_amd64.tar.gz` asset from the [v1.5.0](https://github.com/flashbots/mev-boost/releases/tag/v1.5.0) release was updated yesterday, 17 March 2023;  the hash in the `checksums.txt` file does not match. All other assets' hashes are correct.

`mev-boost_1.5.0_linux_amd64.tar.gz` hash in `checksums.txt` is `69cfd91fe2df3ddd67a2cfeee600d39263498d0ba0aee3fa4c39caf56d788dfb`, I compute it to be `6356098bdf466cb7907e09a31e9d369a899685f4aa1830f950c2e5ac32b01bec`

At least one of the release's assets need to be updated.

**Comment by metachris** [comment]
That's correct, I made a mistake when updating the release it didn't seem to use the new checksums.txt file i've uploaded.

Can confirm that `6356098bdf466cb7907e09a31e9d369a899685f4aa1830f950c2e5ac32b01bec` is the expected hash. Will update the release and make sure it's correct now.

🙏

**Comment by metachris** [comment]
done, fixed checksums.txt, it's correct now. i think the problem was that i both removed the old checksums.txt and added a new one in a single step.

thanks for the report.
