### ISSUE TITLE
Add a unique request ID to `getHeader` and `getPayload` calls.

### ISSUE THREAD

**Issue by michaelneuder** [flashbots/mev-boost#492]
From the relay perspective, it is quite difficult to determine when a validator for a specific slot calls `getHeader`. Because `getHeader` is a public API and the builders use it to check the value of the highest bid, there is a large amount of noise in the logs. Over the last hour, there have been 673k calls to `getHeader` on the ultra sound relay. In order to try to correlate these calls to `getPayload` requests, we can look at the IP addresses of the requests, but this is inconvenient and we would rather not handle that type of PII. 

Collecting data on when a proposer calls `getHeader` is useful because it provides insight into (1) the network latency between the validator and the relay, (2) durations for how long signing headers takes for different validators, (3) if any validators are systematically playing latency games to try to increase the amount of MEV they earn by calling `getHeader` later into the slot (See [ROP-0](https://efdn.notion.site/e57d2e4d207a43c4abdaef71456e59ae?v=3aa44b30109a40aa90f2119d60c4d075&p=385f0f6279374a90b52bf380ed76a85b&pm=s)). 

If we randomly generated a UUID for each proposer for each slot, we would be able to identify which `getHeader` calls are associated with the `getPayload` that ends up being delivered by the relay. Because `getPayload` requires a signature verification of the proposer, we can start there and then scrape our logs for calls to `getHeader` with the same UUID.

**Comment by metachris** [comment]
This would be very helpful in diagnosing issues at the relays!
