### ISSUE TITLE
Allow disabling the relay public key check

### ISSUE THREAD

**Issue by parithosh** [flashbots/mev-boost#499]
It would be useful for pure testing purposes to allow for disabling the relay public key check. This would allow us to setup the entire infra in one go rather than setting up the relay, fetching the public key and then configuring the mev-boost instance.

**Comment by ralexstokes** [comment]
I think this is what you are looking for? https://github.com/flashbots/mev-boost/blob/main/cli/main.go#L62

**Comment by parithosh** [comment]
afaik that's a flag to check for the wellformedness public key, i'd like to pass a flag that lets me provide a relay endpoint without a public key at all. i.e, `--relays 192.168.1.1:58100`

**Comment by ralexstokes** [comment]
I think several things assume there is always a public key for the relay:

require non-empty pubkey: https://github.com/flashbots/mev-boost/blob/main/server/relay_entry.go#L44

verify pubkey in bid matches relay: https://github.com/flashbots/mev-boost/blob/main/server/service.go#L361

check relay signature over bid: https://github.com/flashbots/mev-boost/blob/main/server/service.go#L367

Can you just have a default public key instead?

**Comment by ralexstokes** [comment]
im not as familiar with the relay ops yet but it looks like you can just provide a BLS secret key, look at the docs to run a relay here:  https://github.com/flashbots/mev-boost-relay#running-postgres-redis-and-memcached

so if you can just hardcode a secret key (even just the one in the linked docs), you'll have a known public key you can use in the config

**Comment by metachris** [comment]
I think the easiest would be to have an environment variable that simply skips the signature check for bids.

**Comment by parithosh** [comment]
Yea a skip check variable would be amazing! That's also allow us to use the mock builder from Mario/etc without having to add the functionality of the predefined secret key in there.

**Comment by metachris** [comment]
added a PR: #504

**Comment by metachris** [comment]
The PR is now merged into the `main` branch, and you can skip relay signature checks by using the env variable `SKIP_RELAY_SIGNATURE_CHECK=1`.

**Comment by parithosh** [comment]
Thank you very much! I'll close this issue in that case :)
