### ISSUE TITLE
Please linux-arm64 binary as part of release. Please, pretty please!

### ISSUE THREAD

**Issue by chrishobcroft** [flashbots/mev-boost#507]
We are the parts of the community building on resource-contrained devices, and supporting minority chip architectures, and we wish to participate in this emerging economy by evangelising a `stakeFromHome` mindset, with low-footprint devices that plug into your home router, and act as your node.

We have some experiments going on, such as ethereumonarm.org [EthereumOnARM](https://github.com/diglos/ethereumonarm) (@diglos) building "Ethereum Universe running on a small single-board computer, and swapbox.cash (https://gitlab.com/TrueLevel) building an open-software open-hardware Crypto Cash machine.

Our hardware runs client software from many other web3 projects, including prysm, geth, swarm, arbitrum, livepeer, as well as prometheus, grafana and node_exporter for monitoring.

But the thorn in our side, is our inability to quickly test the configuration of `mev-boost` into our architecture, due to the need, the requirement, to install golang, and git, and all the stuff you need to roll your own binary, then you do the right things and you roll your own binary, even as part of an early prototyping phase.

My request, nay me plea, is that you release a linux-arm64 binary for me to just `wget` in my build script, and you are through the gate and mev-boost is in the party. Thank you friends. Keep up the fine work y'all doing with OFAC n'all!

**Comment by metachris** [comment]
This is already added, here's the build for the latest release: https://github.com/flashbots/mev-boost/releases/tag/v1.5.1-alpha1
