### ISSUE TITLE
Should mev-boost to call getPayload on all relays (instead of only those which sent the bid)?

### ISSUE THREAD

**Issue by metachris** [flashbots/mev-boost#530]
Could be useful for additional data availability -- in case relay which sent the bid can't retrieve the payload, other relays might still possess them, even if they haven't sent the bid.

Only downside I can see is that it will cause light additional load and logging on all relays, if getPayload gets called on all of them for most slots. Doesn't seem big of a downside really.

**Comment by ralexstokes** [comment]
the reason we need this just kind of speaks to the brittleness of this layer of the stack, and ideally we would just work to harden this layer of the stack

at the same time, I think there will also be _some_ risk that this proposal would nullify and I agree the costs for the relays is fairly minimal

we can also make changes to the relay code base to minimize the logging etc

**Comment by benhenryhunter** [comment]
I feel that this is pretty important for standard redundancy along with the increase in recent instability of beacon clients.

There is a bit of uncertainty that a beacon client could be running properly for a relay at any given time.

edited to add that I don't think we should have two sets of relays in mev-boost though one for headers and one for payloads... just seems unstable.

**Comment by metachris** [comment]
Discussed in detail in mev-boost community call #4, agreed to do.
