### ISSUE TITLE
Missing block proposal due to late inclusion

### ISSUE THREAD

**Issue by Neq900** [flashbots/mev-boost#544]
mev-boost[1446]: time="2023-07-09T12:51:**47.346**+02:00" level=info msg="http: GET /eth/v1/builder/header/6839657/0x717236ab3c866d23d2456cb0eb26ec4443655eadb8cfcd0d066988f8a0d1508a/0xa4c0aa10574634b297291afa6381b6f7988d68c1231ad7d661ddc4e3811955dd8bcb187e7ca30ab2ca293f6782340d27 200" duration=0.261881 method=GET path=/eth/v1/builder/header/6839657/0x717236ab3c866d23d2456cb0eb26ec4443655eadb8cfcd0d066988f8a0d1508a/0xa4c0aa10574634b297291afa6381b6f7988d68c1231ad7d661ddc4e3811955dd8bcb187e7ca30ab2ca293f6782340d27 status=200 version=v1.6

mev-boost[1446]: time="2023-07-09T12:51:**50.955**+02:00" level=debug msg="getPayload request starts" method=getPayload version=v1.6

mev-boost[1446]: time="2023-07-09T12:51:50.965+02:00" level=info msg="submitBlindedBlock request start - 3965 milliseconds into slot 6839657" blockHash=0xd3a7f536bceeebb3031aaddaae6b82727b590b1609dc4e8d963847ee0c495088 genesisTime=1606824023 method=getPayload msIntoSlot=3965 parentHash=0x717236ab3c866d23d2456cb0eb26ec4443655eadb8cfcd0d066988f8a0d1508a slot=6839657 slotTimeSec=12 slotUID=af58d3ed-1f7d-43c4-b891-2270e0dd28cc ua=Prysm/v4.0.6/a75e78ddb42a8142763552c3799097c20c02e5d0 version=v1.6

What happens between the first two lines in terms of the delay which is around 3.9 seconds? Why did that happen? It's definitely not my internet connection or slow hard disk.

I'm getting the impression that for now it's better to disable mev-boost as it got quite unreliable since v1.6.

**Comment by michaelsproul** [comment]
> What happens between the first two lines in terms of the delay which is around 3.9 seconds? Why did that happen? It's definitely not my internet connection or slow hard disk.

That delay is coming from whatever your consensus client (Prysm?) is doing to build and sign the block. The Prysm beacon node might be waiting on your execution node for a local payload to compare against, or your Prysm validator client might have taken a long time to sign it (e.g. if it's on a different machine with high latency).

You could try following up with the Prysm devs and sharing some logs

**Comment by Neq900** [comment]
I did that together with others in the [prysm issues](https://github.com/prysmaticlabs/prysm/issues/12513) and it seems that there is a bug in terms of Intel NUCs and the CPU types that are being used by that hardware.
[Related discord](https://discord.com/channels/755466764501909692/997147374067646604).

**Comment by ralexstokes** [comment]
feel free to reopen if there is more to discuss here but it sounds like this is not directly a mev-boost issue
