### ISSUE TITLE
Mev-Boost does not deliver bid if one of many relays are down

### ISSUE THREAD

**Issue by dewindtk** [flashbots/mev-boost#591]
Title describes the issue. Is this intended? Thx in adv

**Comment by ralexstokes** [comment]
I think not but it should be pretty easy to write a unit test to verify this... do you have logs or something to back up your observation?

**Comment by paulperegud** [comment]
I think I've encountered the same (similar?) problem. Logs are here: https://gist.github.com/paulperegud/25302de4a965f1f6f98c1c02259f6735

**Comment by ralexstokes** [comment]
one thing that would help would be running with debug logs @dewindtk @paulperegud 

I'm trying to review the code to see if anything sticks out

**Comment by paulperegud** [comment]
I've turned on `-debug`, to see more logs.

I've also added a test checking what happens if one of relays answers with garbage. The test is green. https://github.com/paulperegud/mev-boost/tree/one-of-many-relays-returns-garbage-test.

**Comment by ralexstokes** [comment]
@paulperegud thanks! going off of your logs, it looks like bloxroute had an error (so no bid) and ultrasound didn't have a bid prepared for this slot (cross-referencing https://relay.ultrasound.money/relay/v1/data/bidtraces/builder_blocks_received?slot=7764853)

so the behavior for that slot is expected

**Comment by metachris** [comment]
Agree, it looks everything is working even if one relay is down.
