### ISSUE TITLE
Determine version currently deployed programmatically via API

### ISSUE THREAD

**Issue by hdelatorre** [flashbots/mev-boost#601]
Is there an API that would do a simple HTTP GET and return the current version?

**Comment by ralexstokes** [comment]
~I don't believe so, but the status endpoint could be changed to send over the version string along with any other helpful client metadata~

just checked and I was incorrect -- the version is set in the header to the status call

https://github.com/flashbots/mev-boost/blob/bdabd0e6181990f9c3e0fef9f750b40f71d50c6c/server/service.go#L255
