### ISSUE TITLE
Upcoming MEV-Boost Release: v1.7 (Deneb)

### ISSUE THREAD

**Issue by metachris** [flashbots/mev-boost#605]
We are preparing an upcoming mev-boost release: v1.7

- This release upgrades mev-boost for [Deneb (EIP-4844: Shard Blob Transactions)](https://www.eip4844.com/).
- An alpha version of v1.7 will be recommended to run for the Goerli Dencun upgrade (happening on 2024-01-17 ~UTC 6:30am)

### Links
- Working branch: [release/v1.7](https://github.com/flashbots/mev-boost/tree/release/v1.7)
- Changelog: https://github.com/flashbots/mev-boost/compare/v1.6...release/v1.7
- Latest tag: [v1.7-alpha1](https://github.com/flashbots/mev-boost/releases/tag/v1.7-alpha1)
- [Docker image](https://hub.docker.com/r/flashbots/mev-boost/tags): `flashbots/mev-boost:1.7a1`

```bash
docker pull flashbots/mev-boost:1.7a1
```

### Notes

- PR with core Deneb changes: #553 
- Goerli Dencun Announcement: https://blog.ethereum.org/2024/01/10/goerli-dencun-announcement
- Big shoutout to @avalonche for a lot of the heavy lifting

**Comment by Sven-NOM** [comment]
What's the status for this alpha release?

**Comment by avalonche** [comment]
Tested on goerli,sepolia and holesky and received payloads across all CLs. Good for goerli fork

**Comment by philknows** [comment]
Just want to confirm here that there's no additional changes we're waiting for and can continue using [`v1.7-alpha1`](https://github.com/flashbots/mev-boost/releases/tag/v1.7-alpha1) for Sepolia + Holesky forks?

**Comment by navillanueva** [comment]
> Just want to confirm here that there's no additional changes we're waiting for and can continue using [`v1.7-alpha1`](https://github.com/flashbots/mev-boost/releases/tag/v1.7-alpha1) for Sepolia + Holesky forks?

Same

**Comment by metachris** [comment]
Planning to release v1.7 once the shadow fork starting on 2024-02-22 has been successful.

**Comment by metachris** [comment]
Not expecting any additional updates to v1.7-alpha1

**Comment by avalonche** [comment]
Released: https://github.com/flashbots/mev-boost/releases/tag/v1.7
