### ISSUE TITLE
Problem since you updated the flashbots relay the 25th of JAN 9 PM UTC

### ISSUE THREAD

**Issue by DaddyGG** [flashbots/mev-boost#617]
Hi everyone,

I am testing some stuff with flashbots on the Goerli testnet. I have been doing that for several months without any problem.

For some reasons now, i cannot call eth_callbundle anymore on the testnet Goerli. It triggers an error and stop me from any further test i need to do since yesterday.

Here is the response body i get now when calling this method → {“id”:10,“jsonrpc”:“2.0”,“error”:{“code”:-32000,“message”:“err: %!w(\u003cnil\u003e); txhash 0x952e025cdc76e8b39fdeb087fdbbd35e83d6fe16e0356f0351d1ba04e998d689”}}

BTW the eth_sendbundle method is working fine.

On the mainnet the eth_callbundle method is working like a charm, so i assume it comes from goerli only.

Do you have an idea why this problem appeared yesterday ? Do you have any solution about it ? Thank you very much for your help and have a great day.

Best regards,

**Comment by ralexstokes** [comment]
I'd try posting in the flashbots discord, this is not the best place for this
