### ISSUE TITLE
Use BLSPublicKeys for the list of relays

### ISSUE THREAD

**Issue by elopio** [flashbots/mev-boost#62]
According to the specification, 

mev-boost is initialized with a list of (BLSPublicKey, RelayURI) pairs representing trusted relays.

But currently we are not using any keys.
https://github.com/flashbots/mev-boost/blob/9912f486df3ecf6f800cf6d847f36e94a12b477e/cmd/mev-boost/main.go#L35

Is this required for the 0.1 release? Or better for the next milestone?

**Comment by elopio** [comment]
Once we have the keys, we should verify the returned [`SignedMEVPayloadHeader`](#signedmevpayloadheader) signature matches the BLS key associated with the IP of the relay and has a matching `payloadId`.

**Comment by ralexstokes** [comment]
relevant: https://github.com/ethereum/builder-specs/issues/23

lets resolve how to handle this type of thing in that issue and I can put it into the spec

**Comment by metachris** [comment]
Addressed by #138 and #143

**Comment by metachris** [comment]
completed
