### ISSUE TITLE
Problem upgrading to latest, need to upgrade Go, add to release notes please

### ISSUE THREAD

**Issue by adv0r** [flashbots/mev-boost#624]
```
 make build
CGO_ENABLED=0 go build -trimpath -ldflags "-w -s -X 'github.com/flashbots/mev-boost/config.Version=v1.6.1-alpha3-13-g39bb78c'" -o mev-boost
go: errors parsing go.mod:
/home/adva/mev-boost/go.mod:3: invalid go version '1.22.0': must match format 1.23
make: *** [Makefile:26: build] Error 1
```

**Comment by avalonche** [comment]
Added to the release notes!

**Comment by EvilJordan** [comment]
I'm confused... the latest stable release of Go is [1.22](https://go.dev/dl/)?

**Comment by avalonche** [comment]
yes need to upgrade go as 1.20 is reaching [EOL](https://github.com/devcontainers/images/issues/944) this month

**Comment by EvilJordan** [comment]
Right, but this says you need 1.23?
> /home/adva/mev-boost/go.mod:3: invalid go version '1.22.0': must match format 1.23

**Comment by EvilJordan** [comment]
Regardless, go v1.22 works just fine :)

**Comment by metachris** [comment]
fixed in latest main/stable branches
