### ISSUE TITLE
Different version number to 1.7

### ISSUE THREAD

**Issue by riordant** [flashbots/mev-boost#626]
on branch `stable` (`39bb78c6ad8e17d5baa53518ec159a686046d953`), can successfully build. 

But - the version should be 1.7 (for dencun upgrade), however the version number is as follows:

```
❯ ./mev-boost -version
mev-boost v1.6.1-alpha3-13-g39bb78c
```

Please indicate if this is the right version for Dencun compatibility.

**Comment by adv0r** [comment]
Ok, the same happened to me (as reported in #625 )

**Comment by avalonche** [comment]
Try `git checkout v1.7` and it should output the right tag

**Comment by riordant** [comment]
```
❯ git fetch
❯ git checkout v1.7
error: pathspec 'v1.7' did not match any file(s) known to git
```

**Comment by riordant** [comment]
yes that works for the tagged version, thanks. but `stable` does not have the same version number

**Comment by arbora** [comment]
As reported above - getting v1.6.1 when I build stable, and additionally I cannot checkout v1.7, even after a git fetch --all

**Comment by metachris** [comment]
Thanks for the report! When building with `make`, the incorrect version number comes from a non-fast-forward merge of the release branch, which messed up the version. 

You can see the correct version in https://github.com/flashbots/mev-boost/blob/39bb78c6ad8e17d5baa53518ec159a686046d953/config/vars.go#L11 but `make` uses the version from git ([see here](https://github.com/flashbots/mev-boost/blob/39bb78c6ad8e17d5baa53518ec159a686046d953/Makefile#L1)) which currently is `v1.6.1-alpha3-13-g39bb78c` on the stable branch (and `v1.6.1-alpha3-13-g54e45da` on the develop branch).

The best way to proceed is by updating to a v1.7.1 patch release with the correct fixes.

**Comment by metachris** [comment]
A v1.7.1 patch version is pushed and tagged -- both `stable` and `develop` branches are synced up on c2a5d00.

The `stable` branch had to be rebased, since it diverged from the `develop` branch. 

You might need to pull with rebase enabled: `git pull -r`
