### ISSUE TITLE
Mergemock is not calling engine_forkchoiceUpdatedV1

### ISSUE THREAD

**Issue by elopio** [flashbots/mev-boost#63]
This should probably tracked in the mergemock repo, but just adding it here for now so we don't lose it.

**Comment by lightclient** [comment]
Close with https://github.com/protolambda/mergemock/pull/17

see: https://github.com/lightclient/mergemock/blob/960e5a477d23984f028f01c00f8959452f369994/consensus.go#L396-L402

**Comment by elopio** [comment]
Thank you friend!
