### ISSUE TITLE
Specify feeRecipientBalance or feeRecipientDiff

### ISSUE THREAD

**Issue by elopio** [flashbots/mev-boost#64]
The [specification](https://github.com/flashbots/mev-boost/wiki/Specification) mentions feeRecipientBalance but the implementation calls it feeRecipientDiff

**Comment by metachris** [comment]
Further down in the spec it's called `feeRecipientDiff`: https://github.com/flashbots/mev-boost/wiki/Specification#mevpayloadheader

Which should it be?

**Comment by elopio** [comment]
Highlighted also by @djrtwo in https://notes.ethereum.org/WX1hwcMRRzy5oh-zHyzqOA?view#step-3

**Comment by thegostep** [comment]
Either works. I suggest picking whichever is most intuitive.

**Comment by metachris** [comment]
If there's no vote against it I suggest we go with `feeRecipientDiff`.
