### ISSUE TITLE
Binary version mismatch: Available version (1.7) lags behind stable version (1.7.1)

### ISSUE THREAD

**Issue by washosk** [flashbots/mev-boost#659]
I noticed that the currently available binary version of mev-boost (1.7) does not align with the latest stable version (1.7.1).
To ensure  users have access to the most up-to-date and reliable version, I kindly request that the maintainers update the available binary to reflect the latest stable version (1.7.1).

Thank you for your time and consideration.

**Comment by metachris** [comment]
See https://github.com/flashbots/mev-boost/issues/626
