### ISSUE TITLE
Replace payloadId with PayloadAttributesV1

### ISSUE THREAD

**Issue by elopio** [flashbots/mev-boost#67]
In https://github.com/flashbots/mev-boost/pull/20#discussion_r774768060 @thegostep suggests:

Should this just be the full PayloadAttributesV1 to avoid confusion?

this was supported by @terencechain and @realbigsean with :+1: , so lets just do it.

**Comment by metachris** [comment]
Closing because the API's have moved on and this is no longer applicable.
