### ISSUE TITLE
v1.8.0 go install failure (Found (v1.8.0), but does not contain package github.com/flashbots/mev-boost)

### ISSUE THREAD

**Issue by EvilJordan** [flashbots/mev-boost#678]
```
$ CGO_CFLAGS="-O -D__BLST_PORTABLE__" go install github.com/flashbots/mev-boost@latest
go: downloading github.com/flashbots/mev-boost v1.8.0
go: github.com/flashbots/mev-boost@latest: module github.com/flashbots/mev-boost@latest found (v1.8.0), but does not contain package github.com/flashbots/mev-boost
```

**Comment by hernanilr** [comment]
$ CGO_CFLAGS="-O -D__BLST_PORTABLE__" go install github.com/flashbots/mev-boost@v1.8.0
go: downloading github.com/flashbots/mev-boost v1.8.0
go: github.com/flashbots/mev-boost@v1.8.0: module github.com/flashbots/mev-boost@v1.8.0 found, but does not contain package github.com/flashbots/mev-boost

**Comment by EvilJordan** [comment]
This works:

`CGO_CFLAGS="-O -D__BLST_PORTABLE__" go install github.com/flashbots/mev-boost/cmd/mev-boost@latest`

Looks like the `README.md` needs to be updated with the correct path. Unfortunately, I'm in bed and can't make a PR right now 😄 

Thanks to @mcdee at Attestant for solving!

**Comment by metachris** [comment]
Argh, it looks like this is related to https://github.com/flashbots/mev-boost/pull/660

I believe I tested installing it with `go install` after this change, but it seems some issue is still there. @MariusVanDerWijden could you open a PR to fix the root `main.go` file to make `go install` work?

**Comment by metachris** [comment]
(think this issue was closed because of the PR merge, but i'd prefer to keep this issue open until confirmed and released)

**Comment by metachris** [comment]
made a patch release v1.8.1 which fixed this, you can now install MEV-Boost again with `go install github.com/flashbots/mev-boost@latest`
