### ISSUE TITLE
SignedBlindedBeaconBlock as JSON-RPC

### ISSUE THREAD

**Issue by elopio** [flashbots/mev-boost#69]
From https://github.com/flashbots/mev-boost/pull/20#discussion_r797521898:

@[tersec](https://github.com/tersec) tersec [on Feb 2](https://github.com/flashbots/mev-boost/pull/20#discussion_r797521898)

This is JSON-RPC serialized, while SignedBlindedBeaconBlock is only specified here as an SSZ type. Aspects of SSZ type serialization aren't otherwise specified by the engine API spec on which this builds, such as SignedBlindedBeaconBlock.signature and SignedMEVPayloadHeader.signature (both BLSSignatures), leaving room for noninteroperability across implementations.

https://github.com/ethereum/execution-apis/blob/v1.0.0-alpha.6/src/engine/specification.md#executionpayloadv1 provides an explicit mapping between a JSON-RPC-serialization of engine.ExecutionPayloadV1 and SSZ representation of bellatrix.ExecutionPayload, where both are supposed to be otherwise isomorphic.
Contributor
@[realbigsean](https://github.com/realbigsean) realbigsean [on Feb 25](https://github.com/flashbots/mev-boost/pull/20#discussion_r815053241)

I agree this should be in JSON-RPC terms.

We could fully specify blocks [here](https://github.com/ethereum/beacon-APIs/blob/master/types/altair/block.yaml), similar to how ExecutionPayloadV1 is defined by the execution API, but that might not be worth doing and maintaining because we already have blocks specified https://github.com/ethereum/beacon-APIs/pull/194, and I don't think we'd want to leave room for discrepancy between JSON serialization of the same type between the two APIs.

I've raised a PR here to add Bellatrix types to the beacon API as well as endpoints and types necessary for blind transaction signing.
Member
@[elopio](https://github.com/elopio) elopio [14 days ago](https://github.com/flashbots/mev-boost/pull/20#discussion_r828124570)

Thanks @tersec and @realbigsean. I need help here to understand the proposal of using JSON-RPC for encoding these new methods. As I understand, SSZ is the new encoding for the consensus layer. I wonder why do we want to use the old encoding for the new things. Probably this has been discussed long ago, so please be patient with me :)
The way I imagine it, these APIs will be implemented by new software in the future, so these seems like a good way to start moving the future to be more consistent and easier to read. Am I being naive or missing some part of the story?
@[tersec](https://github.com/tersec) tersec [14 days ago](https://github.com/flashbots/mev-boost/pull/20#discussion_r828241350)[](https://github.com/tersec)

SSZ is used as as the intra-consensus layer/inter-beacon-node serialization over the libp2p gossip network, yes.

JSON-RPC serializations appear in the REST API and related areas, e.g., validator clients mostly use JSON-RPC-type encodings to interact with beacon nodes. Both remain in use.
@elopio
tersec

**Comment by metachris** [comment]
Closing this as the APIs have moved on and the rationale for the current spec is described in #76. We can reopen if there's additional comments or inputs 🙏
